### ISSUE TITLE
작업물의 부분 부분을 태그 달 수 있는 기능

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#1]

**Comment by papav-hub** [comment]
![Uploading image.png…]()
예상 그림

**Comment by papav-hub** [comment]
![image](https://user-images.githubusercontent.com/67986703/144719811-0eed5a5b-6233-478a-9b2e-cc8119696e87.png)
원하는 결과물 그림

**Comment by papav-hub** [comment]
이미지 픽셀 관련 자료
https://opencv-python.readthedocs.io/en/latest/doc/06.operation/operation.html

**Comment by papav-hub** [comment]
이미지 파일 조작
https://minisp.tistory.com/4

**Comment by papav-hub** [comment]
이미지 마우스 클릭하면 좌표값 추출
https://gaussian37.github.io/vision-opencv-coordinate_extraction/

**Comment by papav-hub** [comment]
<< swift 버전 찾아올것 >>

**Comment by Jimin731** [comment]
작업물 부분 태그 Swift.ver
: Swift의 이미지를 다루는 함수들, 이미지의 비트맵 데이터화, 명도조절, 색감조절, 리사이징 등 가능
- https://soooprmx.com/9652-2/
- https://soooprmx.com/9670-2/ 
- https://youtu.be/S9fbO9l4mVM (이미지파일을 픽셀로 변환하는 영상, 위 내용과 같음)
- https://youtu.be/j-ZLDEnhT3Q (이미지를 픽셀로 변환하여 명도조절, 색감조절 등 여러 효과를 주는 영상)

**Comment by Jimin731** [comment]
- 픽셀화 한 결과 -> int 값 return https://stackoverflow.com/questions/33768066/get-pixel-data-as-array-from-uiimage-cgimage-in-swift
- 픽셀값 찍어오기 -> 특정 픽셀 값의 색상 변경 에 대한 자료밖에 없음. 
- https://pythonq.com/so/ios/198726 (중간 pixelBuffer에서 x, y 좌표값과 이미지에 대한 너비x높이 값은 구할 수 있다.)

**Comment by papavhub** [comment]
Pixel DB에 저장하기
