### ISSUE TITLE
Swift Server

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#10]

**Comment by xoghk5746** [comment]
3. swift에서 앱 디렉토리 생성 및 접근 가능 여부
https://jiseobkim.github.io/swift/2019/07/11/swift-File-Manager.html <- 파일매니저로 폴더 및 디렉토리 생성
https://daesiker.tistory.com/62 <- 파일매니저 디렉토리 생성 가이드
https://hcn1519.github.io/articles/2017-07/swift_file_manager <- 디렉토리 생성 가이드2

**Comment by Jimin731** [comment]
https://nashorn.tistory.com/entry/Swift%EC%99%80-SQLite-%EC%97%B0%EB%8F%99 - iOS와 DB 연결 코드(Swift) , 자료는 mysql이지만 참고하면 좋을 것 같음

**Comment by Jimin731** [comment]
Swift server 조사(깃과 연동되어야 함)
- https://github.com/aws-amplify/aws-sdk-ios (AWS가 제공하는 SDK를 이용하여 Swift로 iOS 모바일 앱 개발 가능.)
- Swift - gitLab 연동 가능.
- Swift에서 자주 사용되는 서버 프레임워크 - Vapor/Perfect/Kitura
- https://yagom.net/forums/topic/swift-%EC%84%9C%EB%B2%84-%EC%82%AC%EC%9D%B4%EB%93%9C-%ED%94%84%EB%A0%88%EC%9E%84%EC%9B%8C%ED%81%AC-vapor-perfect-kitura/ (세 서버를 비교한 사이트. Vapor만 제대로 생성이 됨.)
- 세 서버로 깃 허브와 연동은 많이 하나 깃 서버 구축한 사례는 없음.

**Comment by Jimin731** [comment]
https://youtu.be/r_Ofc9saV60
iOS & node.js 연결
