### ISSUE TITLE
프로토타입

### ISSUE THREAD

**Issue by papav-hub** [kpuce2022CD/CACA#13]

**Comment by xoghk5746** [comment]
https://ovenapp.io/project/eLWyotLGUwgVjHdr3oMHf8zvTj0grtwa#fbPtW

**Comment by pjy7814** [comment]
https://ovenapp.io/view/dyBUF0axmqOO3TCxJhoIECNPQM2m4nRb/

**Comment by papav-hub** [comment]
https://ovenapp.io/view/4qQH9UM435AfWqgwU3RyAytOp0SZreVZ/

**Comment by Jimin731** [comment]
https://ovenapp.io/view/VkkjIVvRJfe5Zsbl1cip7AZ3eRxon6Vi/

**Comment by xoghk5746** [comment]
https://ovenapp.io/project/eLWyotLGUwgVjHdr3oMHf8zvTj0grtwa#fbPtW

**Comment by xoghk5746** [comment]
앱 최종 : https://ovenapp.io/view/eLWyotLGUwgVjHdr3oMHf8zvTj0grtwa/fbPtW
