### ISSUE TITLE
API

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#14]

**Comment by papav-hub** [comment]
pavi03@kpu.ac.kr

**Comment by xoghk5746** [comment]
penline01@naver.com

**Comment by pjy7814** [comment]
pjy0619@kpu.ac.kr

**Comment by Jimin731** [comment]
petitejini@kpu.ac.kr

**Comment by papav-hub** [comment]
- Anazon simple storage service > action
- Amazon s3 control

* CreateAccessPoint 액세스 포인트를 생성하고 지정된 버킷과 연결
* CreateAccessPointForObjectLambda 객체 Lambda 액세스 포인트 생성
* CreateBucket 새 outposts 버킷 생성 / 버킷을 생성하면 버킷 소유자가 됨 / outposts 버킷을 생성하려면 outposts에 s3가 있어야 함
* CreateJob s3r 객체에 대한 대규모 배치 작업(s3 객체 목록에 대해 단일 작업 실행) 수행 입력값 : aws 계정 id
* CreateMultiRegionAccessPoint 다중 지역 액세스 포인트를 생성하고 지정된 버킷과 연결
* DeleteAccessPoint 지정된 액세스 포인트 삭제
* DeleteAccessPointForObjectLambda 지정된 객체 Lambda 액세스 포인트 삭제
* DeleteAccessPointPolicy 지정된 액세스 포인트에 대한 액세스 포인트 정책 삭제
* DeleteAccessPointPolicyForObjectLambda 객체 Lambda 액세스 포인트에 대한 리소스 정책 제거
* DeleteBucket outposts 버킷의 amazon s3 삭제 / 버킷 자체를 삭제하려면 먼저 버킷의 모든 객체를 삭제해야함
* DeleteBucketLifecycleConfiguration 지정된 Outposts 버킷에서 수명 주기 구성을 삭제
* DeleteBucketPolicy Outposts 버킷에서 지정된 Amazon S3의 정책을 삭제
* DeleteBucketTagging Outposts 버킷에서 태그를 삭제
* DeleteJobTagging S3 배치 작업 작업에서 전체 태그 세트를 제거
* DeleteMultiRegionAccessPoint 다중 지역 액세스 포인트를 삭제
* DeletePublicAccessBlock AWS 계정에 대한 구성을 제거
* DeleteStorageLensConfiguration S3 Storage Lens 구성을 삭제
* DeleteStorageLensConfigurationTagging S3 Storage Lens 구성 태그를 삭제
* DescribeJob 작업에 대한 구성 매개변수 및 상태를 검색
* DescribeMultiRegionAccessPointOperation 다중 지역 액세스 포인트를 관리하기 위한 비동기 요청의 상태를 검색
* GetAccessPoint 지정된 액세스 포인트에 대한 구성 정보를 반환
* GetAccessPointConfigurationForObjectLambda 객체 Lambda 액세스 포인트에 대한 구성을 반환
* GetAccessPointForObjectLambda 지정된 객체 Lambda 액세스 포인트에 대한 구성 정보를 반환
* GetAccessPointPolicy 지정된 액세스 포인트와 연결된 액세스 포인트 정책을 반환
* GetAccessPointPolicyForObjectLambda 객체 Lambda 액세스 포인트에 대한 리소스 정책을 반환
* GetAccessPointPolicyStatus 지정된 액세스 포인트에 현재 공개 액세스를 허용하는 정책이 있는지 여부
* GetAccessPointPolicyStatusForObjectLambda 객체 Lambda 액세스 포인트와 연결된 리소스 정책의 상태를 반환
* GetBucket Outposts 버킷에서 Amazon S3를 가져온다.
* GetBucketLifecycleConfiguration Outposts 버킷에 설정된 수명 주기 구성 정보를 반환
* GetBucketPolicy 지정된 Outposts 버킷의 정책을 반환
* GetBucketTagging Outposts 버킷과 연결된 태그 세트를 반환
* GetJobTagging S3 배치 작업 작업의 태그를 반환
* GetMultiRegionAccessPoint 지정된 다중 지역 액세스 포인트에 대한 구성 정보를 반환
* GetMultiRegionAccessPointPolicy 지정된 다중 지역 액세스 포인트의 액세스 제어 정책을 반환
* GetMultiRegionAccessPointPolicyStatus 지정된 다중 지역 액세스 포인트에 공개 액세스를 허용하는 액세스 제어 정책이 있는지 여부
* GetPublicAccessBlock public access block AWS 계정에 대한 구성을 검색
* GetStorageLensConfiguration Amazon S3 스토리지 렌즈 구성
* GetStorageLensConfigurationTagging Amazon S3 Storage Lens 구성의 태그
* ListAccessPoints 지정된 버킷과 현재 연결된 액세스 포인트 목록을 반환
* ListAccessPointsForObjectLambda 객체 Lambda 액세스 포인트와 연결된 액세스 포인트 목록을 반환
* ListJobs 현재 S3 Batch Operations 작업 및 요청하는 AWS 계정에 대해 지난 30일 이내에 종료된 작업을 나열
* ListMultiRegionAccessPoints 지정된 AWS 계정과 현재 연결된 다중 리전 액세스 포인트 목록을 반환 (최대 100개)
* ListRegionalBuckets (별) 요청의 인증된 발신자가 소유한 Outposts의 모든 Outposts 버킷 목록을 반환
* ListStorageLensConfigurations Amazon S3 스토리지 렌즈 구성 목록
* PutAccessPointConfigurationForObjectLambda 객체 Lambda 액세스 포인트에 대한 구성을 대체
* PutAccessPointPolicy 액세스 정책을 지정된 액세스 포인트와 연결
* PutAccessPointPolicyForObjectLambda 객체 Lambda 액세스 포인트에 대한 리소스 정책을 생성하거나 교체합
* PutBucketLifecycleConfiguration S3 on Outposts 버킷에 대한 새 수명 주기 구성을 생성하거나 기존 수명 주기 구성을 대체
* PutBucketPolicy Outposts 버킷에 Amazon S3 버킷 정책을 적용
* PutBucketTagging Outposts 버킷의 S3에 대한 태그를 설정
* PutJobTagging S3 배치 작업 작업에 제공된 태그 세트를 설정
* PutMultiRegionAccessPointPolicy 액세스 제어 정책을 지정된 다중 지역 액세스 포인트와 연결
* PutPublicAccessBlock PublicAccessBlock AWS 계정에 대한 구성을 생성하거나 수정
* PutStorageLensConfiguration Amazon S3 스토리지 렌즈 구성을 넣는다.
* PutStorageLensConfigurationTagging 기존 Amazon S3 Storage Lens 구성에 태그를 추가하거나 교체
* UpdateJobPriority 기존 S3 배치 작업 작업의 우선 순위를 업데이트
* UpdateJobStatus 지정된 작업의 상태를 업데이트

**Comment by papav-hub** [comment]
- Anazon simple storage service >  Data Types
- Amazon s3 control

* AbortIncompleteMultipartUpload 불완전한 멀티파트 업로드 중단을 위한 컨테이너
* AccessPoint 버킷에 액세스하는 데 사용되는 액세스 포인트
* AccountLevel 계정 수준 Amazon S3 Storage Lens 구성을 위한 컨테이너
* ActivityMetrics 활동 메트릭에 대한 컨테이너
* AsyncErrorDetails 실패한 비동기 작업에 대한 오류 세부정보
* AsyncOperation 비동기 작업에 대한 정보의 컨테이너
* AsyncRequestParameters 비동기 요청과 연결된 요청 매개변수의 컨테이너
* AsyncResponseDetails 비동기 요청에 대해 쿼리할 때 반환되는 응답 세부 정보에 대한 컨테이너
* AwsLambdaTransformation 객체 Lambda 액세스 포인트를 통해 객체를 변환하는 데 사용되는 AWS Lambda 함수
* BucketLevel 버킷 수준 구성을 위한 컨테이너
* CloudWatchMetrics S3 Storage Lens 지표에 대한 Amazon CloudWatch 게시를 활성화하기 위한 컨테이너
* CreateBucketConfiguration 버킷 구성의 컨테이너
* CreateMultiRegionAccessPointInput createMultiRegionAccessPoint 요청 과 관련된 정보의 컨테이너
* DeleteMultiRegionAccessPointInput DeleteMultiRegionAccessPoint 요청 과 관련된 정보의 컨테이너
* EstablishedMultiRegionAccessPointPolicy Multi-Region Access Point에 대해 마지막으로 설정된 액세스 제어 정책
* Exclude Amazon S3 Storage Lens가 제외할 컨테이너
* Include Amazon S3 Storage Lens 구성에 포함되는 컨테이너
* JobDescriptor Describe Job요청에 의해 반환된 작업 구성 및 상태 정보에 대한 컨테이너 요소
* JobFailure (별) 작업이 실패한 경우 이 요소는 작업이 실패한 이유
* JobListDescriptor 작업 목록의 일부로 검색된 단일 작업에 대한 구성 및 상태 정보
* JobManifest 작업 매니페스트에 대한 구성 정보
* JobManifestLocation 매니페스트 개체를 찾는 데 필요한 정보
* JobManifestSpec 매니페스트의 형식
* JobOperation 매니페스트에 나열된 모든 개체에서 이 작업을 수행할 작업
* JobProgressSummary 지정된 작업이 시작된 총 작업 수, 성공한 작업 수 및 실패한 작업 수를 설명
* JobReport 작업 완료 보고서에 대한 구성 매개변수
* LambdaInvokeOperation Lambda Invoke작업에 대한 구성 매개변수
* LifecycleConfiguration Outposts 버킷 수명 주기 구성을 위한 컨테이너
* LifecycleExpiration Outposts 버킷 수명 주기 만료의 컨테이너
* LifecycleRule Outposts 버킷 수명 주기 규칙의 컨테이너
* LifecycleRuleAndOperator Outposts 버킷 수명 주기 규칙 및 연산자의 컨테이너
* LifecycleRuleFilter 수명 주기 규칙의 필터에 대한 컨테이너
* ListStorageLensConfigurationEntry ListStorageLensConfigurationResult의 일부 /  각 항목에는 S3 Storage Lens 구성, 홈 리전, 활성화 여부, Amazon 리소스 이름(ARN) 및 구성 ID에 대한 설명
* MultiRegionAccessPointPolicyDocument 다중 지역 액세스 포인트 액세스 제어 정책
* MultiRegionAccessPointRegionalResponse 단일 다중 지역 액세스 포인트 지역에 대한 상태 정보
* MultiRegionAccessPointReport 지원하는 다양한 지역의 다중 지역 액세스 포인트에 대한 상태 모음
* MultiRegionAccessPointsAsyncResponse 비동기 요청에 대해 쿼리할 때 반환되는 다중 지역 액세스 포인트 세부 정보
* NoncurrentVersionExpiration 현재 버전이 만료된 컨테이너
* NoncurrentVersionTransition (별) 이전 버전 전환을 위한 컨테이너
* ObjectLambdaAccessPoint (별) Amazon S3 버킷에서 변환된 데이터에 액세스하는 데 사용되는 연결된 AWS Lambda 함수가 있는 액세스 포인트
* ObjectLambdaConfiguration (별) 객체 Lambda 액세스 포인트를 생성할 때 사용되는 구성
* ObjectLambdaContentTransformation AwsLambdaTransformation용 컨테이너
* ObjectLambdaTransformationConfiguration 객체 Lambda 액세스 포인트 변환을 생성할 때 사용되는 구성
* PolicyStatus 액세스 포인트 정책이 공용인지 여부
* PrefixLevel 접두사 수준 구성의 컨테이너
* PrefixLevelStorageMetrics S3 Storage Lens에 대한 접두사 수준 스토리지 메트릭에 대한 컨테이너
* ProposedMultiRegionAccessPointPolicy 다중 지역 액세스 포인트에 대해 제안된 액세스 제어 정책
* PublicAccessBlockConfiguration PublicAccessBlock이 아마존 S3 계정에 적용한 구성
* PutMultiRegionAccessPointPolicyInput putMultiRegionAccessPoint 요청 과 연결된 정보의 컨테이너
* Region 다중 리전 액세스 포인트와 해당 리전에 연결된 버킷을 지원하는 리전
* RegionalBucket 리전 버킷의 컨테이너
* RegionReport 다중 리전 액세스 포인트의 일부인 버킷과 리전의 조합
* S3AccessControlList
* S3AccessControlPolicy
* S3BucketDestination (별) Amazon S3 Storage Lens 지표 내보내기 파일이 있는 버킷의 컨테이너
* S3CopyObjectOperation (별) PUT Copy 개체 작업에 대한 구성 매개변수를 포함
* S3DeleteObjectTaggingOperation
* S3Grant
* S3Grantee
* S3InitiateRestoreObjectOperation S3 객체 복원 시작 작업에 대한 구성 매개변수 / S3 배치 작업은 모든 객체를 기본 POST 객체 복원 API로 전달
* S3ObjectLockLegalHold S3 객체 잠금 법적 보류가 S3 배치 작업 작업의 객체에 적용될지 여부
* S3ObjectMetadata
* S3ObjectOwner
* S3Retention S3 배치 작업 작업의 모든 객체에 적용할 S3 객체 잠금 보존 모드를 포함
* S3SetObjectAclOperation Set Object ACL 작업에 대한 구성 매개변수를 포함
* S3SetObjectLegalHoldOperation S3 배치 작업 작업이 모든 객체를 기본 PutObjectLegalHoldAPI 로 전달하는 S3 객체 잠금 법적 보류 작업에 대한 구성을 포함
* S3SetObjectRetentionOperation S3 배치 작업 작업에 대한 객체 잠금 보존 작업에 대한 구성 매개변수를 포함
* S3SetObjectTaggingOperation Set Object Tagging 작업에 대한 구성 매개변수를 포함
* S3Tag
* SelectionCriteria
* SSEKMS
* SSES3
* StorageLensAwsOrg S3 Storage Lens에 대한 AWS 조직
* StorageLensConfiguration Amazon S3 Storage Lens 구성을 위한 컨테이너
* StorageLensDataExport 대상, 스키마 및 형식을 포함하여 S3 Storage Lens 지표 내보내기의 속성을 지정하는 컨테이너
* StorageLensDataExportEncryption S3 Storage Lens 지표 내보내기의 암호화를 위한 컨테이너
* StorageLensTag
* Tagging
* Transition 개체가 지정된 스토리지 클래스로 전환되는 시기를 지정
* VpcConfiguration 액세스 포인트에 대한 가상 사설 클라우드(VPC) 구성.

**Comment by Jimin731** [comment]
** 구글 번역기 돌리셔야합니다 **

- 행위
* 멀티파트 업로드 중단: 해당 업로드 ID를 사용하여 업로드 불가. 이전에 업로드한 부품에서 사용한 스토리지 해제
* CompleteMultipartUpload :  멀티파트 업로드 시작한 다음 UploadPart를 이용하여 모든 파트를 업로드. 후 이 작업을 호출하여 업로드를 완료
* 개체 복사: Amazon S3에 이미 저장된 객체의 복사본을 생성
* 버킷 생성: AWS 액세스 키 ID를 이용하여 새 s3 버킷 생성
* CreateMultipartUpload: 멀티파트 업로드 시작 후 업로드 ID 반환
* 버킷 삭제: S3버킷 삭제. (버킷의 모든 객체 삭제 필요)
* DeleteBucketAnalytics구성: 버킷에 대한 분석 구성을 삭제 (분석 구성 ID로 지정됨).
* DeleteBucketCors: cors 버킷에 설정된 구성 정보 삭제
* 버킷 암호화 삭제: s3 기본 암호화를 제거
* deleteBucketIntelligentTiering: 지정된 버킷에서 액세스 요청 빈도수에 따라 객체의 티어(비용)을 알아서 분류해주는 구성 삭제
* 버킷 인벤토리 구성 삭제: 버킷에서 인벤토리 구성(인벤토리 ID로 식별)을 삭제
* DeleteBucketLifeCycle: 지정된 버킷의 생명주기 구성 삭제(하위 리소스 모두 삭제)
* DeleteBucketMetrics 구성: 버킷에서 Amazon CloudWatch 요청 지표(지표 구성 ID로 지정)에 대한 지표 구성을 삭제합니다. 여기에는 일일 스토리지 메트릭이 포함되지 않습니다.
* DeleteBucketOwnershipControls: OwnershipControlsAmazon S3 버킷에 대해 제거
* 버킷 정책 삭제: 지정된 버킷의 정책을 삭제
* DeleteBucket 복제: 버킷에서 복제 구성을 삭제
* DeleteBucketTagging
* DeleteBucketWebsite: 버킷에 대한 웹 사이트 구성 제거
* 개체 삭제: 객체의 null버전(있는 경우) 제거
* 객체 삭제: 버킷의 객체 삭제. 단일 HTTP 요청을 사용하거나 개체 키를 이용하여 개별 삭제 요청
* DeleteObjectTagging: 지정된 개체에서 전체 태그 집합을 제거
* DeletePublicAccessBlock: PublicAccessBlockAmazon S3 버킷에 대한 구성을 제거
———
* GetBucketAccelerate 구성: AWS S3와 더 빠르게 데이터를 주고받을 수 있는 버킷 수준 기능
* getBucketAcl : acl 하위 리소스를 사용하여 버킷의 ACL(액세스 제어 목록)을 반환
* GetBucketAnalytics 구성: 버킷에서 분석 구성(분석 구성 ID로 식별됨)을 반환
* GetBucketCors: 버킷에 대해 설정된 cors 구성 정보를 반환
* GetBucket암호화: Amazon S3 버킷에 대한 기본 암호화 구성을 반환
* GetBucketIntelligentTiering구성
* GetBucket 인벤토리 구성: 버킷에서 인벤토리 구성(인벤토리 구성 ID로 식별됨)을 반환
* GetBucketLifecycle: 버킷에 설정된 수명 주기 구성 정보를 반환
* GetBucket 위치: 버킷이 있는 리전을 반환
* GetBucketLogging: 버킷의 로깅 상태와 사용자가 해당 상태를 보고 수정할 수 있는 권한을 반환
* GetBucketMetrics구성
* GetBucketNotification 구성
* GetBucketOwnershipControls: OwnershipControlsAmazon S3 버킷을 검색
* GetBucket 정책
* GetBucketPolicyStatus: 버킷이 퍼블릭인지 여부를 나타내는 Amazon S3 버킷에 대한 정책 상태를 검색
* GetBucket복제
* GetBucketRequestPayment: 버킷의 요청 결제 구성을 반환
* GetBucket태깅
* * GetBucket 버전 관리: 버킷의 버전 관리 상태를 반환
* GetBucket웹사이트: Amazon S3에서 웹 사이트를 호스팅하려면 웹 사이트 구성을 추가하여 버킷을 웹 사이트로 구성할 수 있습니다
* 객체 가져오기
* GetObjectLock 구성
* GetObjectRetention: 개체의 보존 설정을 검색
* 헤드 버킷: 버킷이 존재하고 액세스 권한이 있는지 확인
* 헤드오브젝트: 개체 자체를 반환하지 않고 개체에서 메타데이터를 검색
* 목록 버킷: 요청의 인증된 발신자가 소유한 모든 버킷 목록을 반환합니다.
* 목록 개체: 버킷에 있는 객체의 일부 또는 전체(최대 1,000개)를 반환합니다. 요청 파라미터를 선택 기준으로 사용하여 버킷에 있는 객체의 하위 집합을 반환할 수 있습니다.
* ListObjectsV2: 요청 파라미터를 선택 기준으로 사용하여 버킷에 있는 객체의 하위 집합을 반환
* 목록 개체 버전: 버킷에 있는 객체의 모든 버전에 대한 메타데이터를 반환
* PutBucket 알림 구성
* PutPublicAccessBlock: PublicAccessBlockAmazon S3 버킷에 대한 구성을 생성하거나 수정
* 개체 복원: 보관된 객체 사본을 Amazon S3로 다시 복원
* SelectObject콘텐츠: 객체 데이터를 레코드로 구문 분석하고 지정된 SQL 표현식과 일치하는 레코드만 반환

————————
- 데이터 유형
* 불완전한 멀티파트 업로드 중단: 불완전한 멀티파트 업로드가 시작된 후 Amazon S3가 업로드의 모든 부분을 영구적으로 제거하기 전에 대기할 날짜를 지정
* 액세스 제어 정책
* AnalyticsAndOperator: 메트릭 필터를 평가하는 데 사용되는 술어의 결합(논리 AND)
* 버킷: 구현 측면에서 리소스. 버킷 이름은 전역적으로 교유하며 네임스페이스는 모든 Aws계정에서 공유됨
* BucketLifecycle 구성
* 버킷 로깅 상태
* AnalyticsS3BucketDestination
* 버킷
* BucketLifecycle 구성
* 버킷 로깅 상태
* 공통접두사: 디렉토리 구분(예:  notes/summer/July
* 완료 멀티파트업로드
* 완성품
* 질환: 지정된 리디렉션이 적용되기 위해 충족되어야 하는 조건을 설명하는 컨테이너
* 개체 결과 복사
* CORS구성 : Amazon S3 버킷의 객체에 대한 교차 출처 액세스 구성을 설명
* CORSR룰
* CreateBucket 구성 : 버킷에 대한 구성정보
* CSV입력: 압축되지 않은 CSV(쉼표로 구분된 값) 형식 입력 개체의 형식을 지정하는 방법을 설명
* CSV출력
* DefaultRetention : 지정된 버킷에 배치된 새 객체에 대한 기본 객체 잠금 보존 설정을 지정하기 위한 컨테이너 요소
* 삭제 : 삭제할 객체에 대한 정보
* 삭제된 개체 : 삭제된 객체에 대한 정보
* 마커 항목 삭제: 삭제 마커에 대한 정보
* 삭제마커복제: S3가 삭제마커를 복제할지 여부를 지정
* 암호화: 사용된 서버 측 암호화 유형
* 암호화 구성: 복제된 객체의 대상인 Amazon S3 버킷에 대한 암호화 관련 정보를 지정
* 이벤트 종료: 요청이 완료되었으며 더 이상 메시지가 전송되지 않음을 나타내는 메시지
* 기존객체복제: 기존 소스 버킷 객체를 복제하기 위한 선택적 구성
* 필터 규칙: 필터링할 Amazon S3 객체 키 이름과 키 이름의 접미사 또는 접두사를 필터링할지 여부를 지정
* 승인하다: 권한 부여 정보
* 수혜자: 권한이 부여되는 사람
* 인덱스 문서: suffix요소의 컨테이너
* 창시자: 멀티파트 업로드를 시작한 사람을 식별
* 입력 직렬화: 개체의 직렬화 형식을 설명(압축형식 지원)
* JSON입력
* JSON출력
* 수명 주기 구성 : 최대 1000개의 규칙 추가 가능
* 수명 주기 만료 
* 수명 주기 규칙 : 버킷의 개별 객체에 대한 규칙
* 수명 주기 규칙 및 연산자 : 수명 주기 규칙 필터에서 두 개 이상의 술어에 논리적 AND를 적용하는 데 사용
* 수명 주기 규칙 필터
* 로깅 가능: 로그가 저장되는 위치와 Amazon S3가 버킷의 모든 로그 객체 키에 할당하는 접두사를 설명
* 메타데이터 항목: 객체와 함께 저장되는 메타데이터 키-값
* 측정항목: 복제 지표 및 이벤트를 활성화하는 복제 지표 관련 설정을 지정하는 컨테이너
* 멀티파트업로드
* 현재 버전 만료되지 않음: 최신이 아닌 객체 버전이 만료되는 시기를 지정. 만료시 현재가 아닌 객체 버전을 영구적으로 삭제
* NoncurrentVersion전환: S3가 유지할 이전 버전의 수 지정.
* 알림 구성: 버킷의 알림 구성.
* 알림 구성 필터: 개체 키-이름 필터링 규칙 지정
* 물체: 개체의 데이터 & 해당 설명 메타데이터
* 개체 식별자
* 개체 잠금 구성
* ObjectLockLegalHold: 개체에 대한 법적 보존 구성
* 개체 잠금 유지
* 개체 잠금 규칙
* 개체 버전
* 출력 위치: 복원 작업의 출력이 저장되는 위치
* 출력 직렬화
* 소유자: 소유자의 표시 이름 및 ID에 대한 컨테이너
* 소유권 제어
* 소유권 제어 규칙
* 진전: 작업 진행 상황에 대한 정보
* 진행 이벤트: 작업 진행 이벤트에 대한 정보
* 기록이벤트
* 리디렉션: 요청이 리디렉션되는 방법을 지정합니다. 오류가 발생하면 반환할 다른 오류 코드를 지정할 수 있습니다.
* RedirectAllRequestsTo: Amazon S3 버킷의 웹 사이트 엔드포인트에 대한 모든 요청의 리디렉션 동작을 지정
* 복제본 수정
* 복제 구성: 복제 규칙에 대한 컨테이너. 최대 1000개의 규칙 추가 가능. 복제 구성의 최대 크키 2MB 
* 복제 규칙: 복제할 Amazon S3 객체와 복제본을 저장할 위치를 지정
* 복제 규칙 및 연산자: 규칙 필터를 지정하기 위한 컨테이너. 필터는 규칙이 적용되는 개체의 하위 집합
* 복제 규칙 필터: 규칙이 적용되는 개체의 하위 집합을 식별하는 필터
* 요청 진행: 주기적 QueryProgress메시지를 보내야 하는지 여부를 지정하기 위한 컨테이너
* 복원 요청: 복원 작업 매개변수에 대한 컨테이너
* 라우팅 규칙: 리디렉션 동작과 리디렉션이 적용되는 시기를 지정
* S3KeyFilter: 개체 키 이름 접두사 및 접미사 필터링 규칙
* S3위치: 복원 요청 결과를 수신할 Amazon S3 위치를 설명
* 스캔 범위: 레코드를 가져올 개체의 바이트 범위를 지정
* ServerSideEncryptionByDefault: 버킷의 새 객체에 적용할 기본 서버 측 암호화 설명
* 소스 선택 기준: 복제할 소스 개체를 식별하기 위한 추가 필터를 설명하는 컨테이너. 
* 스토리지 클래스 분석: 버킷에 대한 서로 다른 스토리지 클래스 간의 균형을 분석하기 위해 수집하고 사용할 수 있는 액세스 패턴과 관련된 데이터를 지정
* 버전 관리 구성
* 웹사이트 구성

**Comment by Jimin731** [comment]
요약본

* 버킷 생성: AWS 액세스 키 ID를 이용하여 새 s3 버킷 생성
* 버킷 삭제: S3버킷 삭제. (버킷의 모든 객체 삭제 필요)
* 개체 삭제: 객체의 null버전(있는 경우) 제거
* 객체 삭제: 버킷의 객체 삭제. 단일 HTTP 요청을 사용하거나 개체 키를 이용하여 개별 삭제 요청
* GetBucket 버전 관리: 버킷의 버전 관리 상태를 반환
* GetBucket웹사이트: Amazon S3에서 웹 사이트를 호스팅하려면 웹 사이트 구성을 추가하여 버킷을 웹 사이트로 구성할 수 있습니다
* 헤드 버킷: 버킷이 존재하고 액세스 권한이 있는지 확인
* 헤드오브젝트: 개체 자체를 반환하지 않고 개체에서 메타데이터를 검색
* SelectObject콘텐츠: 객체 데이터를 레코드로 구문 분석하고 지정된 SQL 표현식과 일치하는 레코드만 반환
