### ISSUE TITLE
Website 구축 (Domain)

### ISSUE THREAD

**Issue by papav-hub** [kpuce2022CD/CACA#15]
https://www.youtube.com/watch?v=OWAqilIVNgE

**Comment by xoghk5746** [comment]
2. 도메인 구매하여 적용하는 방법
https://webpus.com/domain-guide/ <- 도메인 구매 가이드
https://blog.naver.com/hongganz/222490878817  <- 가이드2

https://coding-factory.tistory.com/481 <- 도메인 구매 사이트 (가비아)
https://customer.gabia.com/manual/domain/273/6653 <- 가비아 고객센터 공식 가이드

https://wordpubl.com/%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%82%AC%EC%9D%B4%ED%8A%B8-%EA%B0%80%EA%B2%A9%EB%B9%84%EA%B5%90/
도메인 구매 사이트 가격 비교

가비아를 가장 많이 사용하는 듯 함.

https://blog.lael.be/post/6070 <- 무료 도메인 발급받는 법. (권장하지 않음)
https://taewooblog.tistory.com/83 <- 무료 도메인2
https://taewooblog.tistory.com/82 <- https 적용법 (무료 도메인2 링크의 연장)
