### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#17]

**Comment by papav-hub** [comment]
- Github relational DB schema
![image](https://user-images.githubusercontent.com/67986703/146982837-d5a43636-1659-4b5b-883e-9bc9755655e3.png)

- URL
https://ghtorrent.org/relational.html

**Comment by xoghk5746** [comment]
1. 서버와 db 연동하는 방법 (동영상 내용 참고)
https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server <- 영상에서 사용한 링크
1 - git 사용자 계정과, ssh 사용자의 디렉토리 생성
2 -  .ssh. 디렉토리에 git 사용자 authorized_keys 파일을 추가
3 - 저장소 초기화 옵션. mkdir, cd, git init 명령어.
4 - 통상적인 원격저장소 push 순서. init, add, commit, remote, push

ssh root@도메인
sudo adduser git -> 비밀번호 및 사용자 정보 입력.
su git -> cd -> mkdir .ssh -> chmod 700 .ssh/
touch .ssh/authorized_keys -> chmod 600 .ssh/authorized_keys

cat .ssh/id_rsa.pub (ssh public key 발급)
https://dejavuqa.tistory.com/139 <- ssh key 발급하고 적용하기

https://chucoding.tistory.com/23 <- ec2와 git 연동
https://ndb796.tistory.com/226 <- ec2에 rds 연동
https://yeonyeon.tistory.com/51 <- ec2 서버에 프로젝트 배포

https://seonbicode.tistory.com/76 <- git 저장소에 서버 올리기

**Comment by papav-hub** [comment]
AWS CodeCommit
AWS CodeCommit은 클라우드에서 자산(예: 문서, 소스 코드, 바이너리 파일)을 비공개로 저장하고 관리하는 데 사용할 수 있는 Amazon Web Services에서 호스팅하는 버전 제어 서비스
https://docs.aws.amazon.com/codecommit/latest/userguide/welcome.html

**Comment by papav-hub** [comment]
swift termianl command run
https://stackoverflow.com/questions/26971240/how-do-i-run-a-terminal-command-in-a-swift-script-e-g-xcodebuild

**Comment by pjy7814** [comment]
Sparse Checkout : 하위폴더만 clone하기
https://www.lesstif.com/gitbook/git-clone-20776761.html

(나중에 필요할까봐 그냥 남겨두겠습니다)

——
보통 이미지 기본 정보만 db에 저장하고 image는 별도로 서버에 저장 (https://okky.kr/article/218429)
- 무료 이미지 호스팅 사이트를 사용할까 했는데 보안상 좋지 않을 것 같음
- 이외에는 AWS S3가 많이 사용됨 (https://jjnomad.tistory.com/15)
- Mysql db에 url 저장 (https://velog.io/@dgk089/AWS-S3%EB%A5%BC-%ED%86%B5%ED%95%B4-DB%EC%97%90-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EB%84%A3%EA%B8%B0)

**Comment by Jimin731** [comment]
* S3 select : 원하는 객체 기반 데이터 질의 기능, 브라우저, iOS 에서 S3 버킷의 사진 보기 기능
- https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photos-view.html (브라우저)
- https://stackoverflow.com/questions/59659353/how-to-display-the-complete-images-from-awss3-bucket-in-ios-swift (iOS)

**Comment by papav-hub** [comment]
- 서버에 이미지 저장
- https://stackoverflow.com/questions/8922056/what-is-the-best-way-to-upload-and-store-pictures-on-the-site
- https://blog.naver.com/PostView.nhn?isHttpsRedirect=true&blogId=titetoto123&logNo=220372352310

**Comment by pjy7814** [comment]
이미지 업로드 - s3
1. Codecommit 과 s3를 따로 깃 서버와 연결해서 codecommit에는 원본 psd파일, s3에는 이미지(png)파일만 올리는 방법
2. codecommit에 올린 파일을 lambda-python을 이용해서 s3에 자동 압축해서 올리는 방법
    - 단, s3는 branch 등이 되지 않기 때문에 codecommit을 필수로 이용해야 함
    - 불필요하게 s3에 이중으로 들어가게 됨
	(https://github.com/0xlen/aws-lambda-python-codecommit-s3-deliver) codecommit to s3 lambda로 검색하면 자료 많이 나옴


- swift에서 s3로 이미지 업로드 튜토리얼 (https://swiftdeveloperblog.com/upload-image-to-aws-s3-bucket-in-swift/)

————————
s3 업로드 -> rds에서 http-url 저장 -> s3에서 해당 url로 가져오기
- 형식: https://s3.amazonaws.com/bucketname/(foldername/)imagename.jpg
- s3에 업로드시 꼭 공개로 업로드 해야 url 접근이 가능함
- 만약에 버킷이름이나 이미지 이름 등을 사용자의 아이디, 커밋 로그 등으로 지정한다면 url저장을 하지 않아도 접근 가능하지 않을까..? 하는 생각입니다.

**Comment by papav-hub** [comment]
- Git 특정 파일만 받기
- 
- aws getFile
- https://docs.aws.amazon.com/cli/latest/reference/codecommit/get-file.html

- Blob metadata
- https://docs.aws.amazon.com/codecommit/latest/APIReference/API_BlobMetadata.html
- Returns information about a specific Git blob object.
- Git Blob(이진 대형 개체)은 각 파일의 내용을 리포지토리에 저장하는 데 사용되는 개체 유형입니다. 파일의 SHA-1 해시가 계산되어 Blob 개체에 저장됩니다. 이러한 끝점을 사용하면 GitHub의 Git 데이터베이스에서 blob 개체를 읽고 쓸 수 있습니다. Blob은 이러한 사용자 지정 미디어 유형을 활용합니다. 여기에서 API의 미디어 유형 사용에 대해 자세히 알아볼 수 있습니다.
- https://docs.github.com/en/rest/reference/git

**Comment by papav-hub** [comment]
1. getblob
2. server
3. s3 + codecommit

**Comment by pjy7814** [comment]
![image](https://user-images.githubusercontent.com/79956705/149804205-3c64ae87-03b0-4d82-978d-7a3009721f81.png)
![image](https://user-images.githubusercontent.com/79956705/149804249-8b81daf1-b67c-4ab5-95ab-0f5676f86e22.png)

**Comment by Jimin731** [comment]
![image](https://user-images.githubusercontent.com/80253983/150085360-ed341817-fa3e-4207-b021-c72b1021bcc8.png)
