### ISSUE TITLE
PSD file

### ISSUE THREAD

**Issue by papav-hub** [kpuce2022CD/CACA#18]

**Comment by papav-hub** [comment]
- ImageMagick
- 이미지 조작을 위한 여러 명령줄 유틸리티
- Gimp나 Photoshop과 같은 프로그램으로 그래픽 사용자 인터페이스(GUI)를 사용하여 한 번에 하나씩 이미지를 편집하는 것과 같은 기능 수행 가능
- PSD외 200개 파일 형식 지원

- 할 수 있는 것
- 노이즈 감소
- 필터
- 색상 관리
- 합성
- 프레임, 테두리 추가
- 모양, 텍스트 추가
- 형식 변환
- 수학적 표현 적용
- 이미지 식별
- 대형 이미지 지원
- 이미지 축소판 배치
- 시각적으로 동일한 이미지를 유사한 해시에 매핑 (이미지 검색)
- 이미지에 설명 또는 텍스트 삽입
- 투명도
- 가상 픽셀 지원


- URL
- 공식 홈페이지
: https://imagemagick.org/
- Github
: https://github.com/ImageMagick/ImageMagick

**Comment by papav-hub** [comment]
- ImageMagick Color Replace
: https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=18196

- Detect colors contained on a image
: https://stackoverflow.com/questions/16104420/image-magick-detect-colors-contained-on-a-image

**Comment by xoghk5746** [comment]
1. psd 파일 형식
https://docs.fileformat.com/image/psd/ <- psd 파일 형식 (간결함)
https://crystalcube.co.kr/130 <- psd 파일 형식에 대한 설명

https://binary-viewer.softonic.kr/ <- 바이너리 뷰어 (파일 형식 분석 목적)

파일 헤더, 컬러 모드 데이터, 이미지 리소스, 레이어 및 마스크 정보, 이미지 데이터로 구성.

**Comment by papav-hub** [comment]
git diff 로 비교하면 결과는 Bitmap으로 나옴
WriteableBitmap Class로 Bitmap 조작 가능
: https://docs.microsoft.com/ko-kr/dotnet/api/system.windows.media.imaging.writeablebitmap?view=windowsdesktop-6.0

**Comment by papav-hub** [comment]
- bitmap 파일 분석
https://webnautes.tistory.com/26
https://minimonk.net/300

**Comment by papav-hub** [comment]
결론!!
- psdiff : psd 파일 변경할 때마다 png 내보내기
- https://filp.github.io/psdiff/
- https://github.com/filp/psdiff

**Comment by papav-hub** [comment]
- git diff는 binary 파일만 차이값 찾아낼 수 있다!
- https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

**Comment by papav-hub** [comment]
git diff 참고

**Comment by papav-hub** [comment]
- psd layer png로 추출
https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=34546
