### ISSUE TITLE
모바일 git 연동

### ISSUE THREAD

**Issue by papav-hub** [kpuce2022CD/CACA#2]
https://congcoding.tistory.com/8

**Comment by Jimin731** [comment]
https://github.com/jelmer/dulwich
git을 직업 호출하지 않고 git repos에 대한 인터페이스를 제공(python)

**Comment by papav-hub** [comment]
ios git client

**Comment by papav-hub** [comment]
https://github.com/andrewromanenco/git.ios
+ 같은 사람이 개발한 Android ver. 있음

clone http/https repository
authentication is supported
locally checkout branches/tags
poll changes from origin
source code highlighting

**Comment by papav-hub** [comment]
!! 가장 유사한 것 !!
working copy (유료)

**Comment by papav-hub** [comment]
Q : iOS의 경우 git 명령을 실행할 수 있습니까?
A : https://stackoverflow.com/questions/35535211/for-ios-is-it-possible-to-run-git-command

**Comment by papav-hub** [comment]
How to Install Git in Ish shell, iphone or ios | iphone Termux | apk add git Command not Found Solve
https://www.youtube.com/watch?v=CX0vdwBPuZ4

**Comment by papav-hub** [comment]
애플리케이션에 Git 넣기 - JGit
JAVA

**Comment by papav-hub** [comment]
!! 비슷함 !!
http://gitdrive.com/

**Comment by papav-hub** [comment]
ios-device-server
https://github.com/badoo/ios-device-server

**Comment by papav-hub** [comment]
관련 git 검색
https://github.com/search?l=Swift&q=git+client&type=Repositories

**Comment by papav-hub** [comment]
https://libgit2.org/

**Comment by papav-hub** [comment]
https://git-scm.com/book/ko/v2/%EB%B6%80%EB%A1%9D-B%3A-%EC%95%A0%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98%EC%97%90-Git-%EB%84%A3%EA%B8%B0-go-git

**Comment by papav-hub** [comment]
1. jgit
2. libgit2
3. go-git

**Comment by papav-hub** [comment]
Litgit2 레퍼런스 조사 - 최혜민
- libgit2
: https://git-scm.com/book/ko/v2/%EB%B6%80%EB%A1%9D-B%3A-%EC%95%A0%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98%EC%97%90-Git-%EB%84%A3%EA%B8%B0-Libgit2
1. 깃 저장소 열기
2. Clone
3. Header 커밋 가져오기
4. add
5. commit 메시지 입력
6. 커밋
7. 커밋 객체 가져와서 사용하기
=> Libgit2 바인딩은 많은 언어로 구현되어 있다. (https://github.com/libgit2)
- Swift bindings to libgit2
: https://github.com/SwiftGit2/SwiftGit2

필수 사용 라이브러리
- cmake
- libssh2
- libtool
- autoconf
- automake
- pkg-config
----------------------------------------1차 완료 결론----------------------------------------
