### ISSUE TITLE
Gitdiff

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#22]

**Comment by pjy7814** [comment]
psd 비교

![image](https://user-images.githubusercontent.com/79956705/147449343-6a6f5f68-7843-4296-acb8-bca9f43752fb.png)

**Comment by pjy7814** [comment]
jpg 비교 
![image](https://user-images.githubusercontent.com/79956705/147449598-eb74b6a6-4f3f-4135-8bce-5f7f801b8d0b.png)

**Comment by pjy7814** [comment]
bmp 비교
![image](https://user-images.githubusercontent.com/79956705/147449718-697eda17-edc8-4920-868e-09202de4cee9.png)

**Comment by pjy7814** [comment]
<git diff image>
https://github.com/ewanmellor/git-diff-image
![image](https://user-images.githubusercontent.com/79956705/147489945-a6bea4b1-973d-4334-a5c2-6a7c55e34a6c.png)
![image](https://user-images.githubusercontent.com/79956705/147490003-c243d006-a786-49aa-a4ef-d2debcfbac2d.png)

**Comment by papavhub** [comment]
Determine difference between two images using CoreImage in a SwiftUI Application
https://github.com/anupamchugh/CoreImageAbsoluteColorDiff/tree/411a966ccf40b1c045e972cab45d2119dee28f57
https://towardsdatascience.com/image-difference-using-computer-vision-in-ios-14-7753b8d61e82

**Comment by papavhub** [comment]
Open CV 
https://seokdev.site/219
