### ISSUE TITLE
WebPage (진행중)

### ISSUE THREAD

**Issue by xoghk5746** [kpuce2022CD/CACA#23]
~~1. 발급한 무료 도메인 clonet.tk 로 테스트 중에 있음.
settings -> pages -> custom domain 에 clonet.tk 입력.
기본 도메인인 https://kpuce2022cd.github.io/CACA/ 에 clonet.tk 나, www.clonet.tk 를 연결.
https://www.freenom.com/en/index.html?lang=en  <- 연결하는 작업을 진행할 사이트.~~

=> 연결 테스트 성공. clonet.tk 로 접속 가능함.

이후에 com이나, co.kr 등의 메이저 도메인을 
사이트 '가비아'를 통해 논의 후 구매 예정

2. 웹페이지는 일단 카카오 오븐과 동일한 형태로 제작 예정.
마크업 언어 : html /  프로그래밍 언어 : Javascript / 스타일 시트 언어 : css

현재 vscode 통한 개인 작성 + 다른 템플릿들과 비교 중.

**Comment by xoghk5746** [comment]
https://programmaticponderings.com/tag/continuous-delivery/
Netflix Nebula 및 Spinnaker를 사용하여 AWS에 Spring Boot 앱 배포

<각 1부, 2부>
https://programmaticponderings.com/2018/05/10/deploying-spring-boot-apps-to-aws-with-netflix-nebula-and-spinnaker-part-1-of-2/
https://programmaticponderings.com/tag/continuous-delivery/

1부와 2부에 걸쳐서, Netflix Nebula 및 Spinnaker를 사용하여
AWS에 Spring Boot 앱 배포하는 과정.

1부)
엔터프라이즈 배포, 배포 도구 분석, 오픈소스 대안에 대한 전반적인 설명

2부)
배포 프로세스 설명 및 데모.
https://github.com/garystafford/spring-postgresql-demo <- 게시글 관련 소스코드
아래는 깃헙 내부의 소스코드 들을 사용하여, 앱 배포하는 일련의 과정.

빌드, 테스트, 패키지, 베이크, 배포 프로세스 순서.

=> 대략적인 웹 페이지 구성 정도만 참고됨. 따로 무엇을 사용할 지 정해야 할듯

**Comment by xoghk5746** [comment]
aws의 rds, s3, ec2 각각 조사 + 홈페이지 관련파일 저장 및 db 연동법 등

아마존 웹 서비스(AWS)는 쉽고 빠른 확장성과, 비용을 절감할 수 있는 플랫폼을 클라우드로 제공
아마존 s3는 데이터(사진, 동영상, 문서)를 버킷 내에 객체로 저장.
ec2는 가상의 컴퓨터 제공. 원격제어 가능. (보통 리눅스 및 윈도우 서버 사용을 의미)
rds는 관계형 데이터베이스

https://velog.io/@dongoc21hj/AWS-S3-EC2-RDS <- rds, s3, ec2 설명
https://program-developer.tistory.com/47         <- 설명2
https://shin-bugkiller.tistory.com/entry/AWS-EC2-RDS-S3%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90

rds, s3, ec2를 활용한 정적 및 동적 웹 페이지 구성
1. 정적 웹페이지 - 메모장 파일 열어보듯이 그대로 봄. 
웹 서버에 저장된 html 문서를 클라이언트에게 전송.
데이터 변경되지 않는 이상, 고정된 웹페이지를 보게됨. 같은 결과 요청 및 응답 받음
ex) 회사소개 및 포트폴리오

2. 동적 웹페이지 - 다른 변수들에 의해서 변경되어 보임.
요청 정보 처리후에 제작된 html 문서를 클라이언트에게 전송
상황, 시간, 요청등에 따라 달라지는 웹페이지
ex) 네이버 블로그, 티스토리, 홈페이지 게시판

동적 웹페이지의 경우, 스크립트 처리기(PHP)와, 데이터베이스(ex MySQL)이 필요함.

★ rds, s3, ec2 활용한 정적, 동적 웹페이지 구성 예시
https://abc2080.tistory.com/entry/S3-EC2-RDS%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%9C-%EC%A0%95%EC%A0%81-%EB%B0%8F-%EB%8F%99%EC%A0%81-%EC%9B%B9-%ED%8E%98%EC%9D%B4%EC%A7%80-%EA%B5%AC%EC%84%B1

https://abc2080.tistory.com/entry/%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C-S3%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%9C-%EC%A0%95%EC%A0%81-%EC%9B%B9-%ED%8E%98%EC%9D%B4%EC%A7%80-%EA%B5%AC%EC%84%B1
클라우드와 s3를 사용하면 버킷에서 파일을 읽어오는 형식이기에, 정적 웹페이지 형태임.

https://abc2080.tistory.com/entry/%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C-EC2%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%9C-%EB%8F%99%EC%A0%81-%EC%9B%B9-%ED%8E%98%EC%9D%B4%EC%A7%80-%EA%B5%AC%EC%84%B1
클라우드와 ec2를 사용하면 동적 웹페이지 형태.

만약 로그인 기능이 빠지고, 작가 개인의 홈페이지를 링크하는 형태라면
정적 웹페이지로 구현하는 방향 고려

**Comment by Jimin731** [comment]
동적 웹 배포
: 요청 정보를 처리한 후에 제작된 HTML 문서를 클라이언트에게 전송
유료인 호스팅 업체가 대다수

* Ec2 + 클라우드 : AWS EC2 Ubuntu에 app.js의 서비스 주소로 요청 시 해당 RDS의 MySQL DB에서 데이터 조회 후 출력
(예시: https://abc2080.tistory.com/entry/%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C-EC2%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%9C-%EB%8F%99%EC%A0%81-%EC%9B%B9-%ED%8E%98%EC%9D%B4%EC%A7%80-%EA%B5%AC%EC%84%B1 )

* AWS Lambda & API Gateway : 서버리스 방법으로 AWS 액세스키 필요. Docker 또는 Docker Desktop에 액세스하여 사용 가능
https://youtu.be/tHwatH9GgnM 

- CMS 기반 : 소프트웨어를 기반으로 웹 사이트를 쉽게 빌드, 업데이트 가능
* WordPress : Ec2, mysql 과 연동하여 사용, 개인 이용시 1개월당 4딸라 (https://jocoma.tistory.com/entry/2-tier-%EA%B5%AC%EC%B6%95-7-wordpress%EB%A1%9C-%EB%8F%99%EC%A0%81-%EC%9B%B9%ED%8E%98%EC%9D%B4%EC%A7%80-%EA%B5%AC%EC%B6%95) 
* Joomla: php기반, mysql에 접근하여 동적 웹페이지 개발 가능
* Drupal: php기반, mysql에서 이용(ec2,rds 에서 Drupal 배포: https://aws.amazon.com/ko/getting-started/hands-on/deploy-drupal-with-amazon-rds/4/ )

난이도/보안/기능 -> 드루팔 > 줌라 > 워드프레스
세 프로그램 모두 ec2에서 이용 가능
