### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by pjy7814** [kpuce2022CD/CACA#24]

**Comment by pjy7814** [comment]
Docker swarm

![docker_swam_mode](https://user-images.githubusercontent.com/79956705/147842197-9da72c8c-21f0-48c4-a5d4-c3d46c25aac4.gif)

: 사용자가 많아지면 서버 과부화로 정상적인 서비스를 제공하기가 어려움, 따라서 여러 대의 도커 호스트들을 마치 하나인 것처럼 만들어주는 Orchestration 도구를 사용하게 됨

Orchestration
1. 스케줄링 : 여러대의 서버에 적당한 리소스 분배를 위해 자동적으로 배포해주는 것
2. 클러스터링 : 다중 서버를 하나의 서버처럼. 사용할 수 있도록 해주는 것
3. 서비스 디스커버리 : 다중 서버에 다중 서비스가 떠있는데 내가 찾고자 하는 서비스가 어느 서버에 어떤 위치에 떠있는지 찾아주는 것
4. 모니터링 : 서버 상태를 체크해주는 것
5. 로깅 : 서버 로그 처리
<img width="876" alt="Compose" src="https://user-images.githubusercontent.com/79956705/147842194-ce7e613f-43bb-4208-a229-77dd15f91f6f.png">

- 가운데 고래가 마스터 노드이고 다양한 서버를 연결 시켜서 마스터 노드가 관리할 수 있도록 함. 
- Swarm 명령어는 마스터 노드가 담당하며 마스터 노드를 통해 컨테이너를 띄움
- cluster를 구성 하기 위해서는 manager-node와 worker-node가 필요
* manger-node (위에 3개)
    * worker-node를 관리
* worker-node (아래 6개)
    * service를 제공
- cluster는 worker node를 묶어서 서비스를 제공
<img width="804" alt="Docker Swarm mode" src="https://user-images.githubusercontent.com/79956705/147842299-46da3be8-c764-4795-84da-d6ca5dc9a3f6.png">
: 도커는 container가 단위지만 도커스웜은 서비스가 단위

설치 및 환경 자료 (https://tech.osci.kr/space/TB/21098791337/Docker+Swarm+%EC%9D%84+%EC%9D%B4%EC%9A%A9%ED%95%9C+Container+Orchestration+%ED%99%98%EA%B2%BD+%EB%A7%8C%EB%93%A4%EA%B8%B0)
aws에서 도커스웜 (https://velog.io/@woo0_hooo/docker-docker-Swarm%EC%9D%B4%EB%9E%80)
클러스터 구축 (https://team-platform.tistory.com/51?category=829379)

**Comment by xoghk5746** [comment]
docker compose

![docker-compose-button](https://user-images.githubusercontent.com/84885298/147863356-9213972f-0d0b-43a1-88eb-8c96e3c2aadb.jpg)

https://engineer-mole.tistory.com/221  <- compose 사용법
https://darrengwon.tistory.com/793 <- 사용법 및 간단한 문법

docker compose는 여러개의 컨테이너로부터 이루어진 서비스 구축, 실행하는 순서를
자동으로 하여 관리를 간단히 하는 기능.

Docker compose를 사용하기 위해서는, 크게 아래의 세 가지 순서.
1) 각각의 컨테이너의 Dockerfile를 작성.
2) docker-compose.yml를 작성하고, 각각 독립된 컨테이너의 실행 정의를 실시
3) "docker-compose up" 커맨드를 실행하여 docker-compose.yml으로 정의한 컨테이너를 개시

compose를 구성하기 위한 yml 파일이 필요.
또한 compose 명령어와, yml 파일 문법 숙지가 필요하다.

크게는 버전, 서비스, 재시작 정책, 이미지 빌드, 환경변수, 볼륨, 링크, 의존성 등에 관한 문법.

**Comment by xoghk5746** [comment]
docker registry

![maxresdefault](https://user-images.githubusercontent.com/84885298/147863373-0cf6f3e9-8fe3-48c8-98d2-0310b0eee2fe.jpg)


https://docs.docker.com/registry/ <- 도커 레지스트리 개요
https://hiseon.me/linux/docker-registry/ <- 구축 방법

도커 이미지 등이 회사 내부에서 비공개적으로 사용되거나, 사설 네트워크 등에서 사용되기 위해서
내부 서버에 도커 레지스트리를 구축.

Registry 이미지 다운로드
아래의 명령어를 사용하여, Registry 도커 이미지를 다운로드.

구축 순서
1) 레지스트리 이미지 다운로드 - docker pull registry

2) Registry 컨테이너 생성 - docker run -d -p 5000:5000 --restart=always --name registry registry

3) 도커 이미지 저장 
docker pull ubuntu  <- 테스트 할 이미지 다운로드

Registry에 저장될 Docker 이미지 이름으로 아래와 같이 태깅. 명령어를 실행하면 로컬에 태깅된 이미지가 생성됨.
docker image tag ubuntu localhost:5000/myfirstimage

태깅된 이미지를 서버에 저장하기 위해서는 아래와 같은 명령어를 사용.
docker push localhost:5000/myfirstimage

4) 도커 이미지 배포
Registry에 저장된 도커 이미지는 아래와 같은 명령어로 다운로드.
docker pull localhost:5000/myfirstimage

5) 레지스트리 삭제
docker container stop registry && docker container rm -v registry 

그 외, 접근 제어 및 로그인 기능 포함.

**Comment by Jimin731** [comment]
* docker engine : 도커 이미지를 생성하고 컨테이너를 실행하는 핵심 기능
- 보통 도커라 하면 클라이언트-서버 애플리케이션인 Docker 엔진을 의미.
- 구조
    -- Docker CLI : 도커 명령을 실행하는 커맨드 라인 도구(명령에 따라 Docker engine API 호출)
    -- Docker Engine API
    -- Docker 데몬
- 클라이언트인 Docker CLI가 Docker engine API를 통해 서버인 Docker 데몬에 처리 요청, 응답
- Docker CLI가 도커 호스트 외부 내부에 있는지 따라 통신 방식이 다름
![Docker Host](https://user-images.githubusercontent.com/80253983/147863486-3b0adbc5-d9b8-48b6-8b56-ea028b4bef06.png)

**Comment by papav-hub** [comment]
- kitematic (최혜민) 
- Docker Toolbox에 포함되어 배포되는 Docker 관리 도구 
- 현재는 개발 중단 docker desktop으로 변경
- kafka (최혜민) 
- 오픈 소스 메시지 브로커 프로젝트 
- 실시간 데이터 피드를 관리하기 위해 통일된, 높은 처리량, 낮은 지연시간을 지닌 플랫폼을 제공

**Comment by papavhub** [comment]
Dockefile Docker-compose Finish!
