### ISSUE TITLE
gateway (로드 밸런싱)

### ISSUE THREAD

**Issue by xoghk5746** [kpuce2022CD/CACA#25]
https://aws.amazon.com/ko/blogs/korea/introducing-aws-gateway-load-balancer-easy-deployment-scalability-and-high-availability-for-partner-appliances/
aws 게이트웨이 로드밸런서 소개 (aws 공식)

AWS Gateway Load Balancer (GWLB)의 작동 방식 및 구성 방법
https://support.bespinglobal.com/support/solutions/articles/16000038691--aws-aws-gateway-load-balancer-gwlb-

게이트웨이 로드 밸런서를 사용하면 방화벽, 침입 탐지 및 방지 시스템, 심층 패킷 검사 시스템과 같은
가상 어플라이언스를 배포, 확장 및 관리가 가능해진다.

![aws 게이트웨이](https://user-images.githubusercontent.com/84885298/147863391-46b6cf72-5d50-44e9-9d2d-78054d5426b5.png)

게이트웨이 로드밸런서 엔드포인트를 사용하여, VPC 경계 간에 트래픽을 안전하게 교환.

인터넷 외부 -> 인터넷 게이트웨이 -> 게이트웨이 로드밸런서 엔드포인트 -> 게이트웨이 로드밸런서
-> 공급자 VPC 인스턴스 -> 게이트웨이 로드밸런서 -> 소비자 VPC 인스턴스

링크 내 엔드포인트 생성 및, 엔드포인트 라우팅 설정에 관한 설명 있음.

**Comment by papavhub** [comment]
https://developer88.tistory.com/304
