### ISSUE TITLE
기능 정리

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#29]
<DB & Server>
- DB 생성
- IAM 

<웹>
- 1. DB 연결(rds)
- 2. 권한 부여(s3+iam) & 로그인 기능
- 3. Contact page 구성 & 포트폴리오 사이트 (파라미터 암호화)
- 4. 웹페이지 배포 & 인스턴스 유형 및 규칙 설정 & 포트 열어주기 및 포트포워딩 & nohup 설정 (SSH 접속 끊어도 서버가 계속 실행되게)

<도커>
- 5. MSA구조 생성. & docker-compose.yml 작성
- 6. 도커 이미지 생성 및 도커 허브에 올리기
- 7. 프로메테우스 연결 & 그래파나 연결
- 8. Alertmanager 연결 & Alert rules 만들기

<앱>
- 1. DB 연결(rds)
- 2. 권한 부여(s3+iam) & 로그인/ Git branch 표시/ 이미지 뷰어 (Photoshop Reader)
- 3. 서버 설치, ImageMagick 설치, Image-diff 설치 자동화
- 4. 리포지토리 생성 & 삭제/ 깃 명령어 구현 & 커밋 되돌리기
- 5. 협업 & 사용자 추가
- 6. 이미지 조작(ImageMagick) {투명도 조절/ 확장자 변경/ 자르기/ 크기 변경/ 기울기/ 배경 제거/ 이미지 왜곡}
- 7. 그림 태그 (사용자 표시)
- 8. 레이어별 태그(이슈) 달기
- 9. Image-diff 사용하여 표기
- 10. 워터마크 추가

**Comment by papav-hub** [comment]
<웹>
    * DB 연결(rds)
    * 권한 부여(s3+iam) & 로그인 <10~15>
    * ———
    * Contact page 구성 & 포트폴리오 사이트 (파라미터 암호화)
    * ———
    * 웹페이지 배포 & 인스턴스 유형 및 규칙 설정 & 포트 열어주기 및 포트포워딩 & nohup 설정 (SSH 접속 끊어도 서버가 계속 실행되게)
    * ———
    * MSA구조 생성
    * ———
    * docker-compose.yml 작성
    * 도커 이미지 생성 및 도커 허브에 올리기
    * ———
    * 프로메테우스 연결 & 그래파나 연결
    * ———
    * Alertmanager 연결 & Alert rules 만들기


<앱>
    * 서버 설치, DB 연결(rds)
    * 권한 부여(s3+iam) & 로그인 <10~15>
    * ———
    * ImageMagick 설치, Image-diff 설치 자동화
    * 리포지토리 생성 & 삭제/ Git branch 표시
    * ———
    * 깃 명령어 구현 & 커밋 되돌리기
    * 협업 & 사용자 추가
    * ———
    * 이미지 뷰어 (Photoshop Reader)
    * Image-diff 사용하여 표기
    * ———
    * 그림 태그 (사용자 표시)
    * 레이어별 태그(이슈) 달기
    * ———
    * 이미지 조작(ImageMagick) {투명도 조절/ 확장자 변경/ 자르기/ 크기 변경
    * ———
    * 기울기/ 배경 제거/ 이미지 왜곡}
    * 워터마크 추가

**Comment by papav-hub** [comment]
<웹>
    * DB 연결(rds)
    * 권한 부여(s3+iam) & 로그인 <10~15>
    * ———
    * Contact page 구성 & 포트폴리오 사이트 (파라미터 암호화)
    * 웹페이지 배포 & 인스턴스 유형 및 규칙 설정 & 포트 열어주기 및 포트포워딩 & nohup 설정 (SSH 접속 끊어도 서버가 계속 실행되게)
    * ———
    * MSA구조 생성. & docker-compose.yml 작성
    * 도커 이미지 생성 및 도커 허브에 올리기
    * ———
    * 프로메테우스 연결 & 그래파나 연결
    * Alertmanager 연결 & Alert rules 만들기
<앱>
    * 서버 설치, DB 연결(rds)
    * 권한 부여(s3+iam) & 로그인 <10~15>
    * ———
    * ImageMagick 설치, Image-diff 설치 자동화
    * 리포지토리 생성 & 삭제/ Git branch 표시
    * 깃 명령어 구현 & 커밋 되돌리기
    * 협업 & 사용자 추가
    * ———
    * 이미지 뷰어 (Photoshop Reader)
    * Image-diff 사용하여 표기
    * 그림 태그 (사용자 표시)
    * 레이어별 태그(이슈) 달기
    * ———
    * 이미지 조작(ImageMagick) {투명도 조절/ 확장자 변경/ 자르기/ 크기 변경/ 기울기/ 배경 제거/ 이미지 왜곡}
    * 워터마크 추가

**Comment by papav-hub** [comment]
* DB 연결(rds) : 6 * 권한 부여(s3+iam) : 15
* 로그인 : 15 
* ———
*  Contact page 구성 : 6
* 포트폴리오 사이트 (파라미터 암호화) : 30
 * ——— 
 * 웹페이지 배포 & 인스턴스 유형 및 규칙 설정 & 포트 열어주기 및 포트포워딩 & nohup 설정 (SSH 접속 끊어도 서버가 계속 실행되게) : 36
  * ——— 
  * MSA구조 생성 : 36
   * ——— 
   * docker-compose.yml 작성 : 16 
   * 도커 이미지 생성 및 도커 허브에 올리기 : 20 
   * ——— 
   * 프로메테우스 연결 : 18
* 그래파나 연결 : 18
 * ——— 
 * Alertmanager 연결 : 18
* Alert rules 만들기 : 18


<앱> 
* 서버 설치, DB 연결(rds) : 40 
* 권한 부여(s3+iam) : 40
* 로그인 : 8
* 다음 스프린트 디자인 : 20
 * ——— 
 * ImageMagick 설치, Image-diff 설치 자동화 : 30 
 * 리포지토리 생성 & 삭제 : 40
* Git branch 표시 : 18
* 다음 스프린트 디자인 : 20 
* ———
 * 깃 명령어 구현 & 커밋 되돌리기 : 44 
 * 협업 & 사용자 추가 : 44
* 다음 스프린트 디자인 : 20
 * ——— 
 * 이미지 뷰어 (Photoshop Reader) : 38 
 * Image-diff 사용하여 표기 : 50
* 다음 스프린트 디자인 : 20 
* ——— 
* 그림 태그 (사용자 표시) : 44 
* 레이어별 태그(이슈) 달기 : 44
* 다음 스프린트 디자인 : 20 
* ———
 * 이미지 조작(ImageMagick) {투명도 조절 : 22
* 확장자 변경 : 22
* 자르기 : 22
* 크기 변경 : 22
* 다음 스프린트 디자인 : 20 
* ———
 * 기울기 : 27
* 배경 제거 : 27
* 이미지 왜곡 : 27 * 워터마크 추가 : 27

**Comment by papavhub** [comment]
<< 2022.01.12 수 >>
- Cloud Server(1) && DB받아와서 로그인(2) (박지영)
- 회원가입(2) && 아이디 비번 찾기(2) (최혜민)
- 권한부여 및 리포지토리 생성 UI (윤지민)
+ iam && S3
+ 대본
- 웹 && node js (강태화)

**Comment by papavhub** [comment]
* DB 연결(rds) : 6 
* 권한 부여(s3+iam) : 15
* 로그인 : 15 
* ———
*  Contact page 구성 : 6
* 포트폴리오 사이트 (파라미터 암호화) : 30
 * ——— 
 * 웹페이지 배포 & 인스턴스 유형 및 규칙 설정 & 포트 열어주기 및 포트포워딩 & nohup 설정 (SSH 접속 끊어도 서버가 계속 실행되게) : 36
  * ——— 
  * MSA구조 생성 : 36
   * ——— 
   * docker-compose.yml 작성 : 16 
   * 도커 이미지 생성 및 도커 허브에 올리기 : 20 
   * ——— 
   * 프로메테우스 연결 : 18
* 그래파나 연결 : 18
 * ——— 
 * Alertmanager 연결 : 18
* Alert rules 만들기 : 18


<앱> 
* 서버 설치, DB 연결(rds) : 40 
* 로그인&회원가입&IDPW찾기(EMAIL) : 8
* 다음 스프린트 디자인 : 20
 * ——— 
 * ImageMagick 설치, Image-diff 설치 자동화 : 30 
 * 리포지토리 생성 & 삭제 : 40
* Git branch 표시 : 18
* 다음 스프린트 디자인 : 20 
* ———
 * 깃 명령어 구현 & 커밋 되돌리기 : 44 
 * 협업 & 사용자 추가 : 44
* 다음 스프린트 디자인 : 20
 * ——— 
 * 이미지 뷰어 (Photoshop Reader) : 38 
 * Image-diff 사용하여 표기 : 50
* 다음 스프린트 디자인 : 20 
* ——— 
* 그림 태그 (사용자 표시) : 44 
* 레이어별 태그(이슈) 달기 : 44
* 다음 스프린트 디자인 : 20 
* ———
 * 투명도 조절 : 22
* 확장자 변경 : 22
* 워터마크 추가 : 27

**Comment by papavhub** [comment]
Finish!
