### ISSUE TITLE
[iOS] clone 경로 

### ISSUE THREAD

**Issue by pjy7814** [kpuce2022CD/CACA#31]
https://newbedev.com/finding-a-saved-file-on-the-simulator

**Comment by papavhub** [comment]
XCODE SIMULATOR
/Users/hyeminchoi/Library/Developer/CoreSimulator/Devices/DFD0A364-55D8-4D46-BE50-D8D2EE57B8B7/data/Containers/Data/Application/2FB3C60C-4E95-438D-B844-25F50024EF61/Documents

**Comment by papavhub** [comment]
[Swift] 원하는 앱의 document 폴더 확인하기
https://jk2b.tistory.com/1
