### ISSUE TITLE
Cloud Server + node.js + RDS

### ISSUE THREAD

**Issue by pjy7814** [kpuce2022CD/CACA#33]
[Cloud Server + node.js]
https://velog.io/@rheey90/AWS-EC2-Node.js-%EC%84%9C%EB%B2%84-%EB%B0%B0%ED%8F%AC

[Cloud Server + RDS]
https://steemit.com/nodejs/@dangen/node-js-aws-rds

**Comment by papavhub** [comment]
[EC2가 Linux일 경우]
https://5equal0.tistory.com/entry/AWS-EC2-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4%EC%97%90-ssh-%EC%A0%91%EC%86%8D-%ED%95%98%EA%B8%B0
