### ISSUE TITLE
그림 확장자 / 수정 확인

### ISSUE THREAD

**Issue by pjy7814** [kpuce2022CD/CACA#4]
**그림 작업하는 확장자를 쉽게 보여줄 수 있도록 한다.(뷰어)**
- 스케치, 포토샵, 일러스트레이터, 클립스튜디오, 프로크리에이트 지원

https://www.convertapi.com/psd-to-jpg <<psd
https://docs.aspose.com/psd/net/ai-to-jpg/ <<ai(일러스트)
프로크리에이트는 지원이 안되어서 psd파일로 export하도록 해야함
sketch도,, 클립스튜디오도,,

**같은 그림이라도 어떤 부분을 누가 수정하였는지 확인 가능하다.**

https://gongdoo.tistory.com/319 (원리)
https://github.com/WinMerge/winmerge (깃허브)
결론 : 가능할 것 같음

**Comment by papav-hub** [comment]
<< 삭제 >>
