### ISSUE TITLE
Terraform

### ISSUE THREAD

**Issue by pjy7814** [kpuce2022CD/CACA#40]
~~Terraform IAM 관리
https://medium.com/@jyson88/terraform-iam-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95-6845d143e336~~

**Comment by pjy7814** [comment]
https://gurumee92.tistory.com/234

**Comment by pjy7814** [comment]
[ Terraform Up&Running ] 테라폼 기본 사용 방법
https://hvho.github.io/2021-08-29/terraform-up-and-running-2

**Comment by papavhub** [comment]
get IDs or IPs of Amazon EC2 instances
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/instances

**Comment by papavhub** [comment]
테라폼(Terraform) 기초 튜토리얼 (AWS EC2, RDS)
https://www.44bits.io/ko/post/terraform_introduction_infrastrucute_as_code

**Comment by papavhub** [comment]
terraform 공식 tutorial
https://learn.hashicorp.com/tutorials/terraform/install-cli?in=terraform/aws-get-started

**Comment by papavhub** [comment]
Terraform Project Structure
https://velog.io/@hyun0820/Terraform-%ED%8A%9C%ED%86%A0%EB%A6%AC%EC%96%BC

**Comment by papavhub** [comment]
Terraform sql_query (Data Source)
https://registry.terraform.io/providers/paultyng/sql/latest/docs/data-sources/query

**Comment by papavhub** [comment]
TerraformKit
https://github.com/fourplusone/TerraformKit/tree/18f68372fd28ffca8324f434e45a3a4b40c42026
