### ISSUE TITLE
Swift Codecommit

### ISSUE THREAD

**Issue by pjy7814** [kpuce2022CD/CACA#43]
https://github.com/soto-archive/aws-sdk-appleos/blob/65f3dbd93c37f88c5a09e70525ea425aa9e5f9df/Sources/AWSSDKSwift/Services/CodeCommit/CodeCommit_API.swift

**Comment by papavhub** [comment]
https://docs.aws.amazon.com/codecommit/latest/APIReference/Welcome.html

**Comment by pjy7814** [comment]
https://wingsnote.com/161

codecommit rsa 키

**Comment by papavhub** [comment]
iam update SSHPublicKey
https://docs.aws.amazon.com/IAM/latest/APIReference/API_UpdateSSHPublicKey.html

**Comment by papavhub** [comment]
ssh-keygen (javascript)
https://www.npmjs.com/package/ssh-keygen

**Comment by papavhub** [comment]
aws-sdk-swift / codecommit
https://awslabs.github.io/aws-sdk-swift/reference/0.x/AWSCodeCommit/Home.html

**Comment by papavhub** [comment]
AWS CodeCommit - 사용 설명서
https://docs.aws.amazon.com/ko_kr/codecommit/latest/userguide/codecommit-user.pdf

**Comment by pjy7814** [comment]
https://velog.io/@kimjjs100/%EB%82%98%EB%A7%8C%EC%9D%98-git-%EC%84%9C%EB%B2%84-%EB%A7%8C%EB%93%A4%EA%B8%B0-2-Local-Server%EC%97%90-SSH-%EC%85%8B%ED%8C%85%ED%95%98%EA%B8%B0

**Comment by pjy7814** [comment]
https://www.youtube.com/watch?v=sAeXpcGCQfI
