### ISSUE TITLE
Git Server 구축

### ISSUE THREAD

**Issue by pjy7814** [kpuce2022CD/CACA#44]
https://www.youtube.com/watch?v=sAeXpcGCQfI

**Comment by papavhub** [comment]
https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols

**Comment by Jimin731** [comment]
https://velog.io/@kimjjs100/%EB%82%98%EB%A7%8C%EC%9D%98-git-%EC%84%9C%EB%B2%84-%EB%A7%8C%EB%93%A4%EA%B8%B0-3-%EC%9B%90%EA%B2%A9%EC%A0%80%EC%9E%A5%EC%86%8C-%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0

**Comment by papavhub** [comment]
ssh로 원격 명령어 실행
https://karl27.tistory.com/52

**Comment by papavhub** [comment]
간단한 쉘 스크립트 (Shell Script) 작성 및 실행
https://cheershennah.tistory.com/177

**Comment by papavhub** [comment]
리눅스 환경변수 설정 및 해제하기
https://www.leafcats.com/201

**Comment by Jimin731** [comment]
https://alphacoder.xyz/git-push-to-an-aws-ec2-remote-using-a-pem-file/
remote 설정 - git remote add ec2server ubuntu@(-ec2주소) amazonaws.com:/home/ubuntu/git/remote/

**Comment by Jimin731** [comment]
1. cp ~/(키페어 경로)/git_Keypair.pem ~/.ssh/id_rsa_ec2
2. ssh-keygen -y -f ~/(키페어 경로)/keypair/git_Keypair.pem > ~/.ssh/id_rsa_ec2.pub
3. eval "$(ssh-agent -s)"
4. ssh-add ~/.ssh/id_rsa_ec2 (-> 이후 키페어 경로 설정 없이 ec2 접속 가능)
5. git remote add ec2server ubuntu@(-ec2주소-) amazonaws.com:/home/ubuntu/git/remote/
6. git push --set-upstream ec2server master

--
clone
git clone ubuntu@(-ec2주소-) amazonaws.com:/home/ubuntu/git/remote/

**Comment by pjy7814** [comment]
https://sjh1253.tistory.com/entry/Ubuntu-build-server-3-git-%EC%84%A4%EC%B9%98-%EB%B0%8F-ssh-http-https-%EC%84%A4%EC%A0%95

**Comment by papavhub** [comment]
AWS ELB(Elastic Load Balancing) 생성 후 EC2 연동 & 외부 도메인 연동
https://twofootdog.tistory.com/29

**Comment by papavhub** [comment]
pem key  없이 접속하기 위한 비밀번호 설정
https://bgpark.tistory.com/85

**Comment by papavhub** [comment]
임시 정리본
------------
[local]
    5  mkdir git
    6  cd git
    7  git init local
    8  cd local
    9  pwd
Git init
   10  git remote add origin ssh://git@ec2-3-34-53-137.ap-northeast-2.compute.amazonaws.com/home/ec2-user/git/
   11  git remote -v
   12  git push
   13  git push --set-upstream origin master



[server(ubuntu)]
mkdir git
 cd git
git init --bare remote

**Comment by papavhub** [comment]
git ssh로 받은 프로젝트를 https 방식으로 변경하기.
https://wedul.site/586

**Comment by papavhub** [comment]
Configure Git Server with HTTP on Ubuntu (자세함)
https://linuxhint.com/git_server_http_ubuntu/

**Comment by papavhub** [comment]
How to Set up the HTTP Git Server for Private Projects - NOPE NOPE NOPE
https://thenewstack.io/how-to-set-up-the-http-git-server-for-private-projects/

**Comment by papavhub** [comment]
[Ubuntu build server 3] git 설치 및 ssh, http, https 설정 - YES YES YES YES
https://sjh1253.tistory.com/entry/Ubuntu-build-server-3-git-%EC%84%A4%EC%B9%98-%EB%B0%8F-ssh-http-https-%EC%84%A4%EC%A0%95

**Comment by papavhub** [comment]
http 만들기 명령어 정리

1. sudo apt-get update
2. sudo apt-get install git
3. sudo apt-get install apache2 —— 기본 저장소 만들기
4. Cd /var/www/html/
5. Sudo mkdir git-repositories
6. Cd git-repositories —— 각각의 저장소 만들기
7. Sudo mkdir test.git
8. Cd test.git
9. sudo git init --bare --shared —— git http 설정
10. sudo mv hooks/post-update.sample hooks/post-update
11. Sudo chmod a+x hooks/post-update
12. sudo chown -R ubuntu:www-data /var/www/html
13. sudo chmod -R g+sw /var/www/html
14. sudo a2enmod cgi alias env rewrite
15. sudo vi /etc/apache2/sites-available/000-default.conf (파일 수정)
16. htpasswd -c /var/www/html/.htpasswd ubuntu
17. sudo service apache2 restart ----
18. 80번 포트 열기
19. 끝

**Comment by papavhub** [comment]
sudo service apache2 restart
sudo service apache2 restart
sudo service apache2 restart

**Comment by papavhub** [comment]
15번
SetEnv GIT_PROJECT_ROOT /var/www/html/git-repositoriesSetEnv GIT_HTTP_EXPORT_ALLScriptAlias /git-repositories/ /usr/lib/git-core/git-http-backend/RewriteEngine OnRewriteCond %{QUERY_STRING} service=git-receive-pack [OR]RewriteCond %{REQUEST_URI} /git-receive-pack$RewriteRule ^/git-repositories/ - [E=AUTHREQUIRED]<Files "git-http-backend">     AuthType Basic     AuthName "Git Access"     AuthUserFile /var/www/html/.htpasswd     Require valid-user     Order deny,allow     Deny from env=AUTHREQUIRED     Satisfy any</Files>
