### ISSUE TITLE
SwiftGit2 분석

### ISSUE THREAD

**Issue by Jimin731** [kpuce2022CD/CACA#45]
SwiftGit2

- Create Repositories
Create : url에 새로운 repository 생성
At : url으로 이동하기
Clone: url로부터 clone하기

- Initializers
Init: ‘git_repository’ 객체로 인스턴스 생성
Deinit : 반대

- Remote Lookups
allRemotes : 모든 remote들 Load
remote : 레포지토리로부터 remote road하기
Fetch: git fetch 실행

- Reference Lookups
References: 해당 접두사의 레퍼런스 로드
	- 레퍼런스가 브랜치면 branch 리턴
	- 태그면 TagReference 리턴
localBranches: 모든 로컬 브랜치의 리스트를 리턴
	- localBranch: master 리턴
	- remoteBranch: origin/master 리턴
	- allTags: 모든 태그 리턴

—Working Directory
HEAD : 현재 작업중인 브랜치 리턴
Checkout : 사용할 브랜치로 이동
Commits: 지정된 분기의 모든 커밋을 시간내림차로 로드
unsafeIndex: 리포지토리 인덱스 가져옴
Add: 특정한 위치의 파일(들)을 스테이지에 올림
Commit: 커밋 수행(+메시지를 추가하여 커밋 가능)

— Diffs
Diff : old, new 커밋을 비교

— Status
Status: git status list 반환

— Validity/Existence Check
isValid: url에 깃 리포지토리가 존재한다면 .success(true) 리턴, 없을시 .success(false) 리턴, .failure 에러 발생

**Comment by papavhub** [comment]
https://docs.rs/libgit2-sys/latest/libgit2_sys/struct.git_merge_options.html
