### ISSUE TITLE
추가적으로 적용할 것

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#46]

**Comment by pjy7814** [comment]
로그인 추가 사항

[텍스트 흔들기]
https://velog.io/@dazzlynn/iOS-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85-%EA%B5%AC%ED%98%84-1

**Comment by Jimin731** [comment]
화면 전환 Swipe

**Comment by papavhub** [comment]
- [ ] 레포지토리 List Title (LoginCheck)

**Comment by papavhub** [comment]
- [ ] url 줄이기
https://developers.naver.com/docs/utils/shortenurl/

**Comment by pjy7814** [comment]
- [ ] origin/master -> master 로 자르기
