### ISSUE TITLE
Shell in Swift

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#49]

**Comment by papavhub** [comment]
https://stackoverflow.com/questions/70727026/how-can-i-run-macos-terminal-commands-from-swift#comment125033917_70727026

**Comment by pjy7814** [comment]
https://github.com/kareman/SwiftShell

**Comment by Jimin731** [comment]
https://github.com/AlwaysRightInstitute/Shell

**Comment by pjy7814** [comment]
https://github.com/QiuZhiFei/swift-commands
