### ISSUE TITLE
공부할 책 조사

### ISSUE THREAD

**Issue by xoghk5746** [kpuce2022CD/CACA#51]
1. 공부할 책 조사

1) Docker
가장 빨리 만나는 도커. 기본서의 성격이 강함.
http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9788966188383&orderClick=LAG&Kc=

목차)
1 - 도커 개요 및 컨테이너 설명
2 - 도커 설치 방법
3 - 도커 사용 예제
4 - 도커 이미지 생성하기
5 - 도커 살펴보기
6 - 도커 활용 (이미지 업로드, 저장, 볼륨 컨테이너 사용)
7 - 도커파일 자세히 알아보기
8 - 도커로 애플리케이션 배포하기
9 - 도커 모니터링
10 - Amazon Web Services에서 Docker 사용 (중요)
11 ~ 15 - MS, CoreOS 등 다양한 환경에서 사용
16 - Docker로 워드프레스 블로그 구축
17 ~ 19 - 장고, 루비 등 다른 프레임워크 등 사용 방법 및 시나리오
20 - 도커 명령어 및 옵션 목록

Docker 실전 가이드
http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9788931465273&orderClick=LAG&Kc=

목차)
1 - 도커의 기본
2 - 실전용 도커 이미지 구축
3 - 개발 작업에 적합한 도커 환경 구축
4 - 제 3자가 배포한 도커 이용하기
5 - 도커 기능 구사하기

2) 프레임워크 (Spring). 장고의 경우는 주로 파이썬 환경이라, 스프링으로 조사하였음.

일반적으로 책을 권장하진 않고, 코드 예제를 여러번 타이핑 하는것이 권장된다 함.
자바 초심자의 경우, 바로 스프링 입문서를 보는 것 보다 스프링 예제가 들어있는 자바 관련 도서를 보는게 용이.

자바 -> 스프링 입문서. 후반부에 스프링 관련한 내용 있음. (깊이 들어가지 않을 경우에 용이)
http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9788998139940&orderClick=LAG&Kc=

목차. 세부 내용 다수 존재.)
1~5 - 자바 관련한 이론 및 예제
6 - 스프링 디자인 패턴
7 - 스프링 삼각형과 설정 정보
부록A - 스프링 MVC를 이용한 게시판 구축
부록B - 자바8 람다와 인터페이스 스펙 변화

실습 위주의 책 : 코드로 배우는 스프링 웹 프로젝트
http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9791189184018&orderClick=LEa&Kc=

목차)
1 - 스프링 개발 환경 구축
2 - 스프링 MVC 설정
3 - 기본적인 웹 게시물 관리
4 - REST 방식과 Ajax를 이용하는 댓글 처리
5 - AOP와 트랜잭션
6 - 파일 업로드 처리
7 - Spring Web Security를 이용한 로그인 처리
부록 - 의존성, 톰캣 설정, web.xml, mvc추가 및 xml 파일 생성 등.

**Comment by pjy7814** [comment]
https://book.naver.com/bookdb/book_detail.nhn?bid=15510352
도커 명령어

rxSwift
https://www.youtube.com/watch?v=yafkQ4UYLr4
https://www.youtube.com/watch?v=w5Qmie-GbiA

GraphQL & apollo
https://www.youtube.com/watch?v=9BIXcXHsj0A

**Comment by papavhub** [comment]
- Terraform up & Running
- http://www.kyobobook.co.kr/product/detailViewEng.laf?ejkGb=BNT&mallGb=ENG&barcode=9781492046905


- 실전 카프카 개발부터 운영까지
- http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9791189909345

- 서버/인프라 엔지니어를 위한 DevOps
- http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9791185890760&orderClick=LAG&Kc=

**Comment by Jimin731** [comment]
- http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9791165212308 node js 교과서
- http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9788956747903 완벽한 IT 인프라 구축을 위한 Docker
- https://www.yalco.kr/36_docker/ - 도커 명령어 모음

- https://youtu.be/iJyC6A38qwY - 프로메테우스 익스포트 실습
- https://youtu.be/JWdQp6VrMOw
- https://youtu.be/u5g7j2N6bUM 
- https://youtu.be/xn7t9ZfqZNs  - 스프링부트 + 프로메테우스 + 그라파나 연동(1~3)

**Comment by xoghk5746** [comment]
1. 책 : 코드로 배우는 스프링 웹 프로젝트
http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9791189184018&orderClick=LEa&Kc=

1-1. 스프링 참고 영상
https://www.youtube.com/watch?v=CsOrR-4nH-s&list=PLXAv2-pvdU39y_oRAMbVLYCVu8zmh1iHP&index=1

1-2. 자바 개념 부족할 시 참고 영상
https://www.youtube.com/watch?v=da-GCx8VASU&list=PLieE0qnqO2kTyzAlsvxzoulHVISvO8zA9&index=6

2. 도커
https://www.youtube.com/watch?v=blsebTzOpaw&list=PLgRxBCVPaZ_223caC4aGZyu_LioUqiaio&index=1
