### ISSUE TITLE
Git 예외처리 문구

### ISSUE THREAD

**Issue by ghost** [kpuce2022CD/CACA#52]
예외처리 및 문구
=> 아래의 명령어가 실행되기 위해서는 git init 이라는 명령어가 선행&적용 되어야 함.
사용자가 직접 명령어를 칠 일은 없으니, 타이핑 오류에 관한 경고문구는 생략.

Repo create

중복된 이름의 리포지토리를 만드는 경우
=> 기존에 존재한 저장소가 있습니다.
Add

중복된 이름의 파일을 추가하는 경우
=> 기존에 존재한 파일이 있습니다. or 해당 이름의 파일은 이미 추가되었습니다.
('덮어 씌우시겠습니까' 같은 확인문구 넣어야 할지.)

.get/index.lock 에러 : https://rladuddms.tistory.com/66
=> .get/index.lock 파일 직접적으로 제거함으로 해결 이라는데, 어떻게 예외처리 해야하는지 모르겠음.

Permission denied (권한설정 오류. 윈도우에서 git 설치하고 처음으로 add할 때 발생하는 에러로 추정.)
https://m.blog.naver.com/PostView.nhn?blogId=qls0147&logNo=220863353314&proxyReferer=https:%2F%2Fwww.google.com%2F
=> 위 링크와 같은 지침이 적힌 내용이 담긴 링크 또는 팝업창이 출력 되어 조치될 수 있도록.

git에 종속적인 모듈 있어서 add 안되는 경우.
https://gracefullight.dev/2016/12/27/git-add-%EC%95%88-%EB%90%98%EB%8A%94-%EA%B2%BD%EC%9A%B0-%ED%99%95%EC%9D%B8%ED%95%B4%EC%95%BC%EB%90%A0-%EA%B2%83/
=> 동일하게, 지침이 적힌 내용이 담긴 링크 또는 팝업창이 출력.

commit

폴더 업로드 순서가 잘못된 경우 : https://takeknowledge.tistory.com/64
=> 업로드 될 파일 지정 순서가 잘못되었습니다.
push

저장할 리포지토리의 이름이 올바르지 않은 경우
=> 저장소 이름을 다시 한번 확인해 주세요.

파일을 Add 하지 않은 경우
=> 추가된 파일이 없습니다.

파일을 commit하지 않은 경우
=> 일반적으로 오류는 뜨지 않고, add한 내용이 반영이 안될 뿐이지만,
'원격저장소에 업로드 될 파일 또는 폴더가 지정되지 않았습니다.' 같은 문구 출력되게.

깃허브와 로컬저장소를 동기화하지 않았을 경우 (failed to push some refs to...) : https://yewon918.tistory.com/33
=> 현재 원격저장소와 로컬저장소의 상태가 동일하지 않습니다. 동기화 [fetch(내용 확인) pull(바로 병합)] 를 진행해주십시오.

사용자가 강제로 원격저장소에 push 하려는 경우 : https://aonee.tistory.com/14 (권장하지 않는 이유 설명)
=> 기존에 저장되었던 파일과 히스토리에 영향을 줄 수 있습니다. 정말 진행하시겠습니까? (확인 문구)

어느 브랜치의 데이터를 pull 해올지 지정하지 않아서 발생하는 에러. : https://23life.tistory.com/95
=> 동기화 하려는 저장소 이름을 다시 한번 확인해주세요.

**Comment by papavhub** [comment]
- Revert
- 해당 커밋이 없습니다.
- Merge but no -m option was given 이전 코드들이 머지 되지 않아서 날아갈 수 있습니다. https://dev-syhy.tistory.com/44
- 현재 작업 내용들이 커밋되지 않아서 해당 명령어를 수행할 수 없습니다.

**Comment by pjy7814** [comment]
1. Fetch
    1. 같은 파일 업로드 시 충돌 발생
        1. “기존 작업물을 잃게 될 수 있습니다.” 강제 푸시 (or merge는 안될것같음)
    2.  Nothing to fetch(pull?)
        1. “가져올 자료가 없습니다. 브랜치를 다시 확인해 주세요”
2. Merge
    1. 기본 메시지 “기존 작업물을 잃게 될 수 있습니다.” 후 merge (pull)
    2. 충돌 발생 시 “충돌이 발생 하였습니다. 다시 시도해주세요.” 후 revert를 이용해 병합 취소

**Comment by Jimin731** [comment]
Branch (create delete checkout)
1. 생성
    1. 중복된 이름을 사용하였을때: ‘branch name’이 존재합니다.
2. 삭제
    1. 현재 브랜치를 삭제하고자 할때: ‘branch name’을 사용중이기 때문에 삭제할 수 없습니다. 
    2. 사용중이던 브랜치에서 commit하지 않고 브랜치를 삭제하고자 할때: 변경사항이 저장되지 않았습니다. 
3. 체크아웃
    1. 현재 브랜치로 체크아웃 하고자 할때: 현재 ‘branch name’ 입니다.
    2. 작업물을 커밋하지 않고 branch를 이동할 때 : 전환하기 전에 변경사항을 저장하십시오.

**Comment by papavhub** [comment]
[MERGE_HEAD를 병합한 후 Libgit2가 여전히 .git 폴더에 있습니다.](https://stackoverflow.com/questions/26659195/libgit2-after-merging-merge-head-still-present-in-git-folder)
