### ISSUE TITLE
책 내용 정리

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#53]

**Comment by pjy7814** [comment]
https://yalco.kr/lectures/graphql-apollo


GraphQL은 REST API와 달리 다른 두 개체에 대해서 한번에 쿼리를 보낼 수 있음.
 -> REST API는 두번 따로 보내야 함, 요청이 여러번 반복되는 일을 줄일 수 있음
필요한 정보들만 선택해서 받아올 수 있음 (overfetching 해결)
여러 계층의 정보들을 한번에 받아 올 수 있음 (underfetching 해결)

Query : 불러오기
Mutation : 추가하기, 삭제, 수정

Apollo : GraphQL을 구현하는 솔루션 중 하나
백엔드와 프론트앤드를 모두 제공해서 많이 사용함
React / JS, iOS, Android 모두 제공

——-
Apollo server를 터미널에서 설치 후 index.js파일을 실행했을 때, 서버가 실행되면서 해당 주소로 들어가면 playground를 통해 쿼리를 확인할 수 있음

Apollo server
typeDefs(데이터 구조)와 resolver(액션, 데이터 반환/입력/수정/삭제 수행)를 인자로 받아 서버를 생성

TypeDefs : 데이터 구조
Query : 자료 요청할 테이블
Type : 반환될 데이터의 형태, 필드 (String, Int,,)

Resolver : 데이터를 반환하는 함수 선언 (Java 언어)
where과 같은 쿼리문을 작성하려면 resolve내에서 함수 선언, Typedefs의 query에 지정해야함.
Mapping 또한 마찬가지로 함수를 작성해야 함

Mutation: 데이터 추가/수정/삭제

3-1 강 : TypeDefs와 Resolver 분리해서 테이블 별로 관리하기
3-2강 
<스칼라 타입>
ID : 고유 식별자
String, Int,,,
! : null 반환 금지
< 열거 타입> : 지정된 값만 반환
enum 모듈 추가
<리스트 타입> 특정 타입의 배열 반환 (테이블 내에 배열을 가짐)
<객체 타입> 사용자가 정의한 타입

3-3강
Union : 여러 타입(테이블)을 한 배열로 받아오기
Interface: 공통된 필드를 가진 타입으로 반환하기

3-4강 인자와 인풋 타입
type Query에서 필터링 가능
페이지로 나눠서 받아오기 가능 (3-4강 dbWorks.js참고) & 필터링도 같이 가능
별칭으로 받아오기 가능(데이터를 가공해서 가져오기 가능)
input형식 -> 넣어야할 인자가 많다면 깔끔하게 정리해서 쿼리를 날릴 수 있음 (mutation)

**Comment by pjy7814** [comment]
사진 저장이 안되서 나중에 문서 정리해서 올릴 예정임
RxSwift - SwiftUI수업은 없음(실습은 진행 못함), 공식문서에서 한국어 지원


동기 - 앱 멈추고 서버와 연결해서 가져옴
비동기 - 앱은 안 멈추고 서버에서 가져오는대로 가져옴
DispatchQueue.global().async{ }

대신에 간단한 유틸리티를 사용하자! - 비동기를 처리하는 라이브러리
- PromiseKit -> 리턴을 Promise<>
- RxSwift -> Observable<>을 리턴
=> 비동기식으로 처리하기 위해 간결한 코드를 지원하는 유틸리티


<RxSwift>
Disposable : 취소시키기, 뒤로가기할 때 등등 사용함. 예를 들어, 서버에서 이미지를 불러오다가 함수를 실행시키면 이미지를 가져오지 않음.
DisposeBag : Disposable을 담아서 한번에 취소시킬 수 있음
———-
just : String, array,,, 인자를 넣으면 바로 사용할 수 있게 해줌
From : array를 하나씩 떼어서 내려보내줌
Map : 인자가 내려오면서 중간에 붙여줌. 예를 들어 Hello가 내려오다가 map에서 RxSwift를 만나면 Hello RxSwift가 내려옴. 또는 .count도 가능함. => stream이라고 부름
Filter : true면 내려오고 false면 안내려옴
First: 하나만 받고 그 뒤는 disposable
Concat : 두 String을 합치는데 Complete가 되면 다음 것을 합침

<문서 tip>
| : Complete
X : Error
Decision Tree 이용할 것

Subscribe : 데이터를 사용할 것이라고 선언하기
subscribe(on: (Event<String>) -> Void : 데이터를 받아서 처리함
dispose : 종료시키기
Error 처리 하는 방법임
만약에 위에 코드에서 Single()이 추가되어 있었다면 error발생

Error, complete, dispose -> dispose
귀찮으면
.subscribe(onNext: { },,,)




Scheduler
.observeOn(ConcurrentDispatchQueueScheduler(qos : .default))
데이터를 가져올 때 시간이 오래 걸리는데 가져오기 전에 사용하게 되면 앱이 멈추거나 하지 않음(위치 중요)
.subscribeOn : subscribe 될 때 부터 해당 스케줄러로 돌리는 것 (위치 상관 없음)
.observeOn(MainScheduler.instance) & .subscribeOn(ConcurrentDispatchQueueScheduler(qos: .default)) : 실행 중에 다른 것을 실행 시킬 때 주로 이 조합으로 많이 사용됨

Side-effect
,,,

**Comment by papavhub** [comment]
서버/인프라 엔지니어를 위한 DevOps
- 테스트 자동화
: JUnit, PHPUnit, Selenium
- 지속적 통합 도구 (Pull Request 만으로 가능)
: Jenkins
- 가상 환경 구축 도구 (개발 환경 균질화)
: Vagrant
- 프로비저닝 도구 (인프라 구축 자동화)
: Chef, Ansible
- 모니터링 도구
: Sensu, Zabbix, Nagios
----
- Ansible에 의한 서버 구축
- CircleCI를 이용한 지속적 통합 입문
- Docker / Kubernetes / 클러스터 관리
----
결론
1. 개발 환경 균질화
2. 테스트 자동화
3. 인프라 구축 자동화
4. 지속적 통합
5. 모니터링

**Comment by Jimin731** [comment]
- 노드 시작하기
    - 멀티 스레드 방식에 비해 컴퓨터 자원을 적게 사용
    - I/O 작업이 많은 서버로 적합
    - 싱글 스레드 방식
    - 웹서버 내장
    - 자바스크립트 사용
    - JSON 형식과 호환

- 노드 기능 알아보기
    - REPL : Read, Eval, Print, Loop 미리 컴파일 하지 않아도 즉석에서 코드 실행 가능
    - 모듈: 특정한 기능을 하는 함수나 변수들의 집합
        - Require: 불러올 모듈의 경로 지정
    - 노드 내장객체:
        - Global: 전역 객체, 간단한 데이터를 파일끼리 공유
        - Console: 디버깅 중 사용, 변수 값 내용 확인 에러 내용 표시 등
        - Process : 현재 실행되고 있는 노드 프로세스에 대한 정보
    - 동기 & 비동기: 함수가 바로 return 되는지의 여부
    - 블로킹 & 논블로킹: 백그라운드 작업 완료 여부
    - > 노드는 동기 블로킹 방식과 논블로킹 방식이 대부분.

- http 모듈로 웹 서버 만들기
    - 쿠키: ‘키-값’, 서버는 쿠키를 이용해 사용자가 누구인지 파악
    - REST API: 서버에 대한 자원 정의, 자원에 대한 주소 지정 (GET, POST, PUT, PATCH, DELETE)
    - Cluster: 싱글 스레드인 노드가 CPU 코어를 모두 사용할 수 있게 하는 모듈, 세션을 공유하지 못함

- 패키지 매니저(npm)
    - Package.json: 설치한 패키지 버전을 관리하는 파일, 설치한 패키지들을 지워버려도 이 파일에 내역이 들어있음.

- 익스프레스 웹 서버 만들기
    - Express-generator: 프레임워크에 필요한 package.json을 만들어주고 기본 폴더 구조까지 잡아주는 패키지
        - www: 서버를 실행하는 스크립트
        - Public: 외부에서 접근 가능한 파일(이미지, 자바스크립트, CSS 등)
        - Routes: 주소별 라우터(서버의 로직)
        - Views: 템플릿 파일(화면)
        - Models: 데이터베이스
    - 미들웨어: 요청과 응답의 중간에 위치(라우터, 에러핸들러 등)
        - Express-session: 로그인 등 세션 관리용 미들웨어
    - 템플릿 엔진: 자바스크립트를 이용해 HTML을 렌더링 할 수 있게 함
        - PUG: Ruby와 문법이 비슷함, HTML 문법 변형
        - EJS: HTML문법 그대로 & 자바스크립트 문법 사용

- MySQL: DBMS중 관계형 데이터베이스
    - 시퀄라이즈: ORM, 자바스크립트 객체와 데이터베이스의 릴레이션을 매핑해주는 도구

- 몽고DB: NoSQL- 고정된 테이블 기능, JOIN 기능, 트랜잭션 등을 지원하지 않음, 확장성과 가용성이 좋음
    - 몽구스: ODM- 스키마 생성, JOIN 기능 등 지원

- 서버리스 노드 개발
    - 서버리스: 서버를 클라우드 서비스가 대신 관리해줘서 개발자나 운영자가 서버를 관리하는 데 드는 부담이 줄어들음.
    - S3, Cloud Storage: 정적 파일을 제공할 수 있음
    - Lambda: 람다 트리거를 이용하여 S3에 올린 이미지 리사이징 후 저장

**Comment by xoghk5746** [comment]
**프레임워크 책 - 코드로 배우는 스프링 웹 프로젝트**

스프링 개발 환경 구축
  - JDK 1.8 이상, 톰캣 설치.
  - 스프링 플러그인 설치 (이클립스 이용시)
  - 스프링 프로젝트 생성 (Maven 사용, perspective 스프링으로 지정.)
    => 생성 시, 스프링 MVC Project 이용해서 생성.

  - Lombok 라이브러리 설치. 생성자 등을 자동으로 생성해 주는 역할.
  - 의존성 주입 (xml 방식 또는 java 설정)
  - 관계형 데이터베이스 및 JDBC 연결

스프링 MVC 설정
  스프링 MVC는 스프링의 서브 프로젝트임.

모델2 스프링 MVC의 기본 구조 :

![스프링 MVC](https://user-images.githubusercontent.com/84885298/151824883-7a098de7-7665-4b13-9f59-72ad61c4ad99.jpg)

  - 스프링 MVC 이용하는 경우, 컨트롤러의 특징
  1) HttpservletRequest, HttpservletResponse를 거의 사용할 필요 x
  2) 다양한 방식의 파라미터 처리, 리턴 타입 사용 가능
  3) Get, post 방식 등 전송 방식 처리 -> 어노테이션으로 처리 가능
     (어노테이션은, 소스코드에 추가적 정보를 제공하는 메타데이터.)
  4) 상속/인터페이스 방식 대신에 어노테이션 만으로 필요한 설정 가능.

기본적인 웹 게시물 관리
  - 일반적으로 웹 프로젝트는 3티어 방식으로 구성.
  
![3티어 방식](https://user-images.githubusercontent.com/84885298/151824939-0ef0de01-1982-4a2b-8260-f8d98a583652.jpg)

  1) presentation Tier(화면 계층) : 화면에 보여주는 기술 사용하는 영역 (view와 유사)
  2) Business Tier(비즈니스 계층) : 비즈니스 로직을 담고있는 영역 (controller 역할)
  3) Persistence Tier(영속 계층, 데이터 계층) : 데이터 보관 방식 및 설계 들어가는 영역 (VO, DAO)


파일 업로드 처리
  - 브라우저상에서 첨부파일 처리
   1) <form> 태그 방식 : 브라우저 제한 없는 경우에 사용
   2) <iframe> 방식 : 화면의 이동 없이 첨부파일을 처리
   3) <Ajax> 방식 : 첨부파일 별도 처리. (input file=type 이용하고, Ajax로 처리)

   서버 쪽 첨부파일 처리는, 응답을 html 코드 또는 JSON으로 처리. 이에 대한 구분만 가능하게.
  - 스프링 첨부파일 설정 
    web.xml 이용하는 경우 -> 첨부파일 처리에 대한 설정 역시 web.xml로 처리.
    java 설정 이용  -> 아래와 같은 플러그인 추가.

![JAVA 설정 이용](https://user-images.githubusercontent.com/84885298/151825013-cb408e84-6844-4af8-95fd-276c1afc27fd.jpg)

스프링 웹 시큐리티를 이용한 로그인 처리
  - 스프링 시큐리티는 단독 설정 가능. 
  1) root나 servlet과는 별도로 security-context.xml 따로 작성.
  2) web.xml 설정 <- 필터 이용하여 스프링 동작에 관여하게.
  3) 인증, 권한부여를 통한 접근 제한 설정 (아래 사진 참조)

![접근 제한](https://user-images.githubusercontent.com/84885298/151825050-9d1922f9-d36b-4458-b17e-108480c2f3f0.jpg)


**도커 - 유튜브 링크 및 책 (트러블 슈팅 도커) 참조**

![OS 컨테이너 예시](https://user-images.githubusercontent.com/84885298/151825180-baffd724-7078-464d-8302-6ad40cb7d54e.jpg)


도커는, 컨테이너 기반의 가상화 플랫폼. 어플리케이션을 캡슐화 하여 독립적 운영환경을 제공하는 기술.

우선, 컨테이너를 패키지로 만드는 데 필요한 모든 명령 도커파일에 작성. -> 도커 이미지 빌드.
$ docker build (-f 옵션으로 도커파일의 경로 지정 가능. ex) docker build -f /경로/dockerfile)

$ docker run : 이미지 생성 이후 컨테이너 배치
$ docker pause : 현재 컨테이너에서 구동 중인 프로세스를 일시정지.
$ docker start  : 한개 이상의 정지된 상태인 컨테이너를 실행.
$ docker stop : 컨테이너 사용 완료 시 SIGTERM -> SIGKILL 시그널을 보내어 자연스럽게 종료.
$ docker kill : 강제 종료


도커 볼륨 명령어 도움말
$ docker COMMAND
$ docker COMMAND --help

도커 이미지 검색
$ docker search redis

도커 이미지 다운로드
$ docker image pull [옵션] 리포지토리명[:태그명]

도커 이미지 목록 보기
$ docker image ls

도커 허브 등의 레지스트리에 등록
$ docker image push [옵션] 이미지명:[:태그]

**Comment by pjy7814** [comment]
도커 명령어 정리

docker search : 도커 레지스트리에서 제공하는 이미지 검색 & 실행
옵션  -s : 사용자 피드백 기준으로 널리 사용되는 파일
Docker pull : 도커 레지스트리에서 원하는 이미지를 로컬 머신에 가져오기
태그 지정하지 않으면 latest 태그 간주
Docker images : 현재 로컬 머신에서 사용할 수 있는 최상위 이미지 목록
옵션 -a 
Docker rmi : 요청한 이미지를 로컬 머신에서 삭제 (함께 설치됐던 계층도 포함)
Docker run : 이미지를 다운로드한 수, 이미지를 실행시키는 커맨드
파일 시스템, 포트, IP 주소를 가진 컨테이너 1개 구동
옵션 -i : STDIN을 열어 인터랙티브 모드로 전환
옵션 -t : 가상 tty 콘솔 터미널을 할당
옵션 -d : 프로세스를 분리한 상태(백그라운드)로 구동
Docker ps : 현재 구동 중인 모든 컨테이너 보기
컨테이너 당 하나의 프로세스만 실행
옵션 -a : 현재 구동하지 않는 컨테이너까지 보여줌
Docker logs : 인수로 지정한 컨테이너의 로그 파일
컨테이너 ID로 검색해서 커맨드 히스토리 등을 볼 수 있음
stdout과 stderr로 출력한 내용만 보여줌
Docker restart : 인수로 지정한 컨테이너를 다시 구동
Docker attach : 컨테이너의 셸 프롬프트로 진입할 때 사용, 컨테이너를 제어하거나 현재 출력되는 내용을 확인
Docker remove : 인수로 지정한 컨테이너를 삭제
Docker stop : 멈추고 삭제해야 함. -f 옵션을 사용해도 됨
Docker inspect : 컨테이너나 이미지의 상세하고 낮은 수준의 정보 확인
mySQL 컨테이너의 경우 모든 정보를 JSON 배열로 리턴
Docker exec : 이미 구동중인 컨테이너를 원격에서 실행
Docker rename : 현재 구동 중인 컨테이너의 이름을 바꾸기
Docker cp : 컨테이너와 컨테이너를 구동하는 머신 사이에서 파일을 복사할 때 사용
Docker pause/unpause : 인수로 지정한 컨테이너에 있는 모든 프로세스를 일시적으로 멈추기
Docker create : 인수로 지정한 이미지 위에 쓰기 가능한 컨테이너 계층을 새로 생성 & 다른 인수로 지정한 커맨드 실행 준비
Docker start로 실행 (docker run 아님)
Docker commit : 컨테이너 이미지 새로 생성
컨테이너에 발생한 변경 사항을 반영한 채로 이미지를 만들어 다른 곳에 배포할 수 있음
Docker diff : 베이스 이미지를 기준으로 파일 시스템에서 변경된 사항을 확인 가능

도커 파일
: 이미지를 빌드하는 데 필요한 커맨드로 구성된 파일, 반드시 FROM 인스트럭션으로 시작
.dockerfile

**Comment by xoghk5746** [comment]
책에는 초기 설정 관련한 부분이 없거나, 레거시 기준 설명이라 상이하기에 따로 유튜브 링크 찾아봄.
기존에 참고하였던 링크들은 이클립스 기반. sts 개발이 더 용이하다고 함.

웹 개발에는 이클립스 대신 sts 사용함.
https://www.youtube.com/watch?v=tFkZfw05OmU&t=0s <- 초기 웹 개발환경 설정.

0. 초기 워크스페이스 지정 시에는 c드라이브에 폴더 하나(예 : springtest) 만들고 지정하는것 권장.
  워크스페이스 경로 변경시에는 switch workspace로 변경할 것. (metadata 있어야 하기 때문)

1. sts4 자바 EE플러그인 설치 (jsp 웹 개발환경. jsp, html, css 인식하도록.)
마켓플레이스 ->eclipse web 검색.
eclipse enterprise java.. 설치.
설치 되고있는 도중에는, 다른 작업 하지 않도록 한다.

2. 자바스크립트 파일 인식 설정.
윈도우 -> preferences -> editors -> file associations ->*.js add로 추가.
-> generic text.. 를 default로 설정함.

3. 폰트, 인코딩(UTF-8) 설정
윈도우 -> preferences -> font 검색 -> basic -> text font -> 글꼴 및 텍스트 크기 설정함. (verdana, 14pt 권장)
인코딩은 윈도우 -> preferences -> enc 검색. html, css, jsp, workspace 모두 utf-8로 지정. (오류 피하기 위함)

4. Lombok 플러그인 설치 (생성자를 자동으로 생성하기 위함.)
Lombok 라이브러리 검색. https://projectlombok.org/download <- 해당 링크로 접속.
lombok.jar 파일을 툴에 적용시킬 것. -> 툴을 끄고, 눌러서 설치가 아닌
jar 파일이 있는 폴더에서 우클릭 -> git bash -> java -jar lombok.jar 입력.
어떤 툴에 lombok을 설치할 것이냐? -> sts 실행파일이 있는 곳을 지정.
-> specify location 입력 -> sts 위치한 경로 클릭.

https://www.youtube.com/watch?v=rpcoHCXgGnQ&list=PL93mKxaRDidECgjOBjPgI3Dyo8ka6Ilqm&index=5 <- 의존성 설정
new spring starter project -> 라이브러리 관리는 Maven 으로.
이후, 아래 사진과 같은 항목 6개 체크하여 설치. https://getinthere.tistory.com/16 <- 참조 링크

![의존성](https://user-images.githubusercontent.com/84885298/152199473-4e54457a-8272-49ae-bacb-383b47a4a5f7.png)


중요 : Spirng Web
내장형 컨테이너로, 톰캣을 기본 탑재하고 있음. 웹 mvc를 사용하여, 웹 애플리케이션 만드는데에
필요한 스프링부트의 기본적인 요소를 가짐. -> 레거시 버전에 비해서 톰캣을 따로 설치할 필요가 없음.

이후 pom.xml (의존성 등 들어있는 파일) 로 가서, dependencies에 링크 내부에 있는 의존성 추가. (시큐리티 태그 ~ JSTL)
JSP 템플릿 엔진 의존성은, jasper라는 라이브러리를 추가함으로서, jsp 파일을 인식하게 함.

주의 : src/main/java 내부에 패키지 생성할 때, 임의로 이름 지정하면 안됨.
초기에 설정된 패키지 이름이 com.cos.website 이면, 다른 패키지 이름은 com.cos.website.이름 이 되어야 함.
com.cos.test로 임의로 지어버리면 작동 안함. 싱글톤 패턴 + 레퍼런스 변수 (스프링이 관리하는 제어의 역전)
=> 패키지 이하를 전부 스캔하여 필요한 것들을 메모리에 로드.
즉, 패키지 이름(com.cos.website) 이하만 스프링이 스캔을 진행함. 임의로 지어버리면 스캔할 수 없음.
DAO, VO, Controller 등 만드는 경우에도 com.cos.website.기능이름 으로 지을것!

지속적으로 수정중.
