### ISSUE TITLE
Apollo&GraphQL

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#55]
https://designcode.io/swiftui-advanced-handbook-apollo-graphql-part-1

**Comment by Jimin731** [comment]
https://www.youtube.com/watch?v=6oxS1Z35bE0&ab_channel=DesignCode
Apollo GraphQL with SwiftUI Crash Course

**Comment by papavhub** [comment]
Apollo&GraphQL Query

- [ ] 로그인 : Select * from user (where id=id & pw=pw)
- [ ] 회원가입 : Insert * from user
- [ ] 아이디 찾기 : Select * from user (where email=email)
- [ ] 비밀번호 찾기 : Select email from user (where id=id) -> email 발송
- [ ] 리포 목록 : select repo_name from mapping (where id=id)
- [ ] 리포 생성 : insert * from repository insert * from mapping
- [ ] 사용자 추가 : select * from user (where email=email) insert * from mapping
- [ ] 사용자 프로필 : insert profilePic from user select * from user [RestAPI->S3]
- [ ] 그룹 사용자 : select * from mapping (where repo_name=repo_name)
