### ISSUE TITLE
EC2 설정

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#56]
- Apollo & Graphql
- https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install
- https://yarnpkg.com/package/mysql

**Comment by papavhub** [comment]
- 인증서 SSL (server.crt, server.csr, server.key)
- https://m.blog.naver.com/espeniel/221845133507

**Comment by papavhub** [comment]
- [Error: listen EACCES 0.0.0.0:443](https://stackoverflow.com/questions/50112186/error-listen-eacces-0-0-0-0443)
- sudo setcap 'cap_net_bind_service=+ep' `which node`
- https://stackoverflow.com/questions/50112186/error-listen-eacces-0-0-0-0443

**Comment by pjy7814** [comment]
$ curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ sudo apt remove cmdtest
$ sudo apt remove yarn
$ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
$ sudo apt-get update
$ sudo apt-get install yarn -y
$ yarn install
$ yarn add graphql
$ yarn add shelljs
$ yarn add apollo-server
$ yarn add knex
$ yarn add mysql
