### ISSUE TITLE
Git bare repository에서 읽기

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#58]

**Comment by papavhub** [comment]
파일 읽기
https://stackoverflow.com/questions/59047434/what-does-blob-in-github-correspond-to

**Comment by papavhub** [comment]
파일 리스트 읽기
https://stackoverflow.com/questions/25906192/git-ls-files-in-bare-repository

**Comment by papavhub** [comment]
tree 8d3fcec8f72a829115dba5498185071dae82f389
parent 99199fa0b017667519e2ad39ef99262d6e22b98e
author papavhub <pavi03@kpu.ac.kr> 1644732183 +0900
committer papavhub <pavi03@kpu.ac.kr> 1644732183 +0900
https://velog.io/@gringrape200/%EC%BB%A4%EB%B0%8B%EC%9D%80-snapshot-%EC%9D%B4%EB%8B%A4-diff-%EA%B0%80-%EC%95%84%EB%8B%88%EB%9D%BC

**Comment by papavhub** [comment]
read-blob library
https://github.com/wbinnssmith/read-blob

**Comment by papavhub** [comment]
image를 blob형태로 db에 저장하기
https://logical-code.tistory.com/103

**Comment by papavhub** [comment]
image Blob 객체를 url로 바꾸어 img 띄우기
https://kyounghwan01.github.io/blog/JS/JSbasic/Blob-url/#createobjecturl

**Comment by papavhub** [comment]
특정 커밋에서 목록 및 cat 파일
https://stackoverflow.com/questions/40197455/list-and-cat-files-at-certain-commit)

**Comment by papavhub** [comment]
fetch-blob

https://www.npmjs.com/package/fetch-blob

**Comment by pjy7814** [comment]
$ git ls-files
: 파일 목록 불러오기

$ git cat-file -t 1f7a7a472abf3dd9643fd615f6da379c4acb3e3a
blob
 : 개체 유형 알려주기

$ git cat-file -p 
: blob으로 파일 내용 읽기

**Comment by pjy7814** [comment]
**Binary 파일(image, mp3, mov 등) 처리**

https://javafa.gitbooks.io/nodejs_server_basic/content/chapter10.html

**Comment by pjy7814** [comment]
$ git ls-tree <commit id>
$ git cat-file -p <blob id> > filename.jpeg

**Comment by papavhub** [comment]
[How do I convert a bare git repository into a normal one (in-place)?](https://stackoverflow.com/questions/10637378/how-do-i-convert-a-bare-git-repository-into-a-normal-one-in-place)
