### ISSUE TITLE
비슷한 프로그램 조사

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#6]

**Comment by papav-hub** [comment]
1   Sketch Cloud
- 업로드할 작업공간 여러 개 생성 가능
- 버전 관리와 인스펙터 기능 한 곳에서 사용
- 이전 버전으로 복원하는 기능 없음
2   Abstract
- 리뷰 과정을 거쳐 마스터에 업데이트
- 자체 서버에 저장하기 때문에 로컬에서 파일 잃어버려도 괜찮
- 외부에 화면 공유 기능
- 업로드할 작업공간 여러 개 생성 가능
- 프로젝트의 인덱스 색상 선택 (HEX 코드)
- 프로젝트는 카드형, 목록형으로 확인 가능
- 참여하고 있는 사람들 프로필 사진, 최근 업데이트 날짜
- Drag and Drop
- 뷰어에서는 해당 디자인에 대한 히스토리 확인
- 특정 영역 지정하여 의견 추가
3   Github
- Git Sketch Plugin 추가 도구로 시각적인 차이 비교 가능
- Text 위주
4   Kactus
- UI 디자이너가 쓰기에 더 적합
- 시각적으로 비교할 수 있는 화면 다양 (겹쳐보기 등 4가지)
5   Plant
- 웹앱에서 화면 확인
- 파일 용량 제한 없다
- 선택한 대지만 내보내기
- 스케치 라이버르리 지원
- 마스터 브랜치만 있음
- 작업물 업로드 시, 다른 사람에게 알림
- Join 전에 히스토리 볼 수 없음
6   Folio
- Sketch 뿐만 아니라 Photoshop, Illustrator도 지원
- UI 명확
- 검색 기능
- 마스터 브랜치만 있음
7   Sympli
- 브랜치 기능 있음
- Sketch, Figma, XD, Photoshop, Android Studio의 hand off
- Slack, JIRA와 연동

**Comment by pjy7814** [comment]
https://medium.com/hyuk/디자인-버전-관리-툴-2종-간단-리뷰-a946da74d9fe

Abstract : 표시 & 의견 공유 가능, 바로 sketch에서 편집 가능

- 결제 후 협업이 가능
- 깃에 대한 이해 필수적
Kactus : 깃허브 기반
- 깃허브 이해 필수적
Plant : 웹앱에서 화면 보임, 용량 제한 X
- Join이전의 히스토리는 볼 수 없음
Folio : PSD, Illustrator 지원
- 깃허브 계정과 연결
Simple : 브랜치 기능, 버전관리는 Sketch만 지원
- 딜레이, 화면 이동이 심함

관련 기사
https://it.donga.com/32606/

**Comment by pjy7814** [comment]
- Abstract : 스케치 파일을 버전 관리를 쉽게 하는 프로그램
    - 개인계정은 무료지만 팀사용 시 유료 플랜 이용
    - 주석 사용 가능, @+아이디 팀원에게 피드백 요청 가능
    - Compare 탭에서 이전 버전과 비교하지만 단순하게 사진을 두개 띄워서 보여줌
- Plant : 스케치 파일의 버전 관리 프로그램
    - 웹앱에서 확인이 가능하며 간단한 수정 가능
    - 협업을 위한 주석 기능
    - 버전 비교 가능하지만 단순 비교
- Simpli  : 스케치 파일의 버전 관리 프로그램
    - 웹앱에서 간단한 수정 가능
    - 영역을 선택하여 팀원들과의 의견 공유 가능
    - 스케치, 포토샵, 코드 등 툴이 나누어져 있음 -> 버전관리는 sketch만 가능
- Kactus : 스케치 파일의 버전 관리 프로그램
    - pull 요청, 협업 등 다양한 기능 제공
    - 이전 버전과 비교해주지만 단순 비교만 가능

**Comment by pjy7814** [comment]
결론 : 대표적인 프로그램 4개가 있으며 주로 스케치 파일 위주의 파일이다. 웹앱에서 실행하고 주석 기능을 사용한다. 비교기능을 지원하지만 단순 비교로 좌우로 배치하는 기능이다. 따라서 우리는 PSD파일을 버전 관리하는 앱을 만들 것이며 단순 비교가 아닌 편리하게 비교가 가능하게 만드는 것을 목표로 한다.

**Comment by pjy7814** [comment]
클립스튜디오


사용 이유 : 만화를 주로 집필하는 사람과 작업을 돕는 조수가 동시에 작업을 진행

- 관리자 : 공동작업 파일 설정한 사람
- 이용자 : 관리자로부터 연락을 받고 지정된 파일을 취득해 작업


이용자가 수정완료한 이 후 [공동작업 데이터에 덮어쓰지 않음]으로 되어있다면 업데이트 반영 후 신규 폴더에 편집한 페이지 복사, [작업 폴더 업데이트] 실행하면 편집한 페이지를 경합 파일로 가져옴

- 관리방법
    - 페이지 별로 담당 : 관리자가 이용자의 편집 가능한 페이지와 편집 내용의 반영 모두 관리
    - 공정별로 담당 : 관리자가 이용자의 편집 가능한 페이지를 제한하지 않고 "경합"이 발생한 경우 해소하는 관리 방법

(https://tips.clip-studio.com/ko-kr/articles/1737)

* 장점
    * clip을 이용하는 사용자 간에 빠른 공동 작업
    * 관리자와 이용자를 나누어 충돌에 대한 대응
    * 여러 사용자가 동일한 페이지를 동시에 편집할 수 없게 되어 있어 '경합' 문제가 발생하지 않음
    * 태블릿, 스마트폰 버전 등 모든 기기에서 사용 가능
    * 편집 시 자동으로 동기화 기능 제공
* 단점
    * 설정할 것이 많음
    * 관리자와 사용자가 나뉘어 사용자가 합치기를 못하는 경우 발생
    * clip이외의 공동 작업 불가능
    * 공동 작업시 달라진 부분에 대한 확인이 불가능
    * 주석을 달지 않고 작업하여 의견을 공유할 환경 부족
    * 동기화가 안될 경우가 존재
    * 기존의 클립 스튜디오보다 더 상위의 요금제 사용

**Comment by xoghk5746** [comment]
3. 클립 스튜디오 차이점 단점 장점 조사 + 통계
장점)
다양한 브러시 지원
도구 사용이 쉬운 편임.
스토리 모드 (자신이 만든 모든 페이지와 에피소드 열람 가능)
어두운 테마 옵션 제공

단점)
하나의 파일에 전부 저장하기 때문에 파일에 에러가 날 경우 복구가 상당히 힘들다.
프로그램이 다소 무겁고, 특정 소재를 읽어들일 때 로딩이 길다.
키 바인딩이 복잡하다.
텍스트와 글꼴이 불충분하다.
도구 자체의 사용은 쉬우나, 신규 사용자가 바로 사용하기에 전체적인 인터페이스가 다소 난잡한 편.
일본에서 개발하였기에, 소프트웨어가 일본어로 되어있어서, 사용이 다소 어려울 수 있다.

프로그램과의 차이점)
사용자 친화를 목적으로 했기에, 전체적인 인터페이스가 클립스튜디오에 비해서 간단하게 구현할 예정
프로그램 자체 용량도 가급적 크지 않게 구성할 것
소프트웨어도 영어, 한국어를 사용
스토리 모드에서 보완된, 단순히 작업 내역 열람 뿐만이 아닌 해당 시점으로 작업 되돌리기.
작업한 과정 및 결과를 웹에 연동하여 포트폴리오 화 및 파라미터 암호화 가능. (권한 부여받은 사용자만 접근할 수 있게)

**Comment by Jimin731** [comment]
클립스튜디오 팀작업
https://tips.clip-studio.com/ko-kr/articles/4777

1. 관리자가 팀 생성, 다른 사용자를 팀원으로 초대
2. 클라우드에 업로드한 파일의 [팀 작업] On 설정, 만든 팀을 작업팀으로 설정
3. 팀에 참가한 다른 팀원은 클라우드에서 작품 다운로드 가능
4. 작품 편집 후 캔버스를 닫으면 자동으로 클라우드 동기화 

단점)
팀 작업을 이용하려면 비싼 ex 버전을 사용해야함 . 
여러 사용자가 동일한 페이지를 동시에 편집할 수 없음

장점)
인터넷을 통해 태블릿/스마트폰/pc 버전 등 모든 기기 사용 가능

**Comment by papav-hub** [comment]
- 클립스튜디오의 클라우드 기능 
1. 자동 동기 기능 기기의 작품과 클라우드 작품을 동일하게 하여 최신 상태로 유지 
* 백업용이며, 버전 관리는 되지 않는다. 
2. 그린 작품을 다른 환경에서 편집 
* 다른 툴을 쓰는 사람과는 전혀 호환이 되지 않음 
- 그룹 협업 기능 
* 각각의 작업 내용을 확인할 수 없음 
* 다른 툴을 쓰는 사람과 전혀 협업이 불가능함 
* 버전관리 없음
