### ISSUE TITLE
React

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#60]
React 프로젝트 생성
https://jsikim1.tistory.com/193

**Comment by papavhub** [comment]
[Spring boot + React] Spring boot 와 React 연동하기
https://velog.io/@jung-co/Spring-boot-%EC%99%80-React-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0

**Comment by papavhub** [comment]
[Docker] react + nginx + Dockerizing 
https://hello-bryan.tistory.com/169

**Comment by pjy7814** [comment]
$ npm run build

**Comment by papavhub** [comment]
Docker-compose를 이용한 다중 컨테이너 실행(Dockerfile 활용) : springboot & react 
https://junghwanta.tistory.com/m/52

**Comment by papavhub** [comment]
Create-react-app docker-compose 구성
![image](https://user-images.githubusercontent.com/67986703/153994193-c933590d-0b5d-4cf7-9758-507a87dae347.png)
https://medium.com/sjk5766/create-react-app-docker-compose-%EA%B5%AC%EC%84%B1-b01e1219d14e

**Comment by papavhub** [comment]
ERROR : Error occurred while trying to proxy request
https://velog.io/@aksel26/HPM-Error-occurred-while-trying-to-proxy-request

**Comment by papavhub** [comment]
도커(Docker)를 활용해 React 앱 배포하기 [react_dockercompose_sample]
https://leonkong.cc/posts/dockerizing-react-app.html

**Comment by papavhub** [comment]
https://sundries-in-myidea.tistory.com/112
![image](https://user-images.githubusercontent.com/67986703/154063130-e4337769-933a-438b-b602-f0c1937c7f22.png)

**Comment by papavhub** [comment]
vi /opt/homebrew/etc/nginx/nginx.conf
https://blog.naver.com/PostView.naver?blogId=qjawnswkd&logNo=222398369932&parentCategoryNo=&categoryNo=27&viewDate=&isShowPopularPosts=true&from=search

**Comment by pjy7814** [comment]
docker ip 잡기

https://log-laboratory.tistory.com/204

**Comment by pjy7814** [comment]
react + nginx + Dockerizing

https://hello-bryan.tistory.com/169
