### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#62]

**Comment by papavhub** [comment]
+ docker-compose
https://www.vultr.com/docs/how-to-run-jenkins-on-ubuntu-with-docker-compose/

**Comment by papavhub** [comment]
jenkins setting
https://devlos.tistory.com/34

**Comment by pjy7814** [comment]
[Jenkins]Git 연동하기(Git Token 발급 + Jenkins Credential 등록)

https://velog.io/@zzarbttoo/JenkinsGit-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0Git-Token-%EB%B0%9C%EA%B8%89-Jenkins-Credential-%EB%93%B1%EB%A1%9D
