### ISSUE TITLE
Reload data

### ISSUE THREAD

**Issue by pjy7814** [kpuce2022CD/CACA#63]
https://iphonedev.co.kr/iOSDevQnA/73694
thread나 timer을 이용해서 주기적으로 업데이트하는 방법밖에 없는 듯

- Timer 이용하는 방법
https://maheshsai252.medium.com/updating-swiftui-view-for-every-x-seconds-559360ce3b4a
- Combine의 timer을 이용해서 주기적 업데이트 하는 방법
https://stackoverflow.com/questions/58738443/how-to-refresh-a-view-every-second-using-swiftui

**Comment by papavhub** [comment]
React 개념을 생각해보면 Timer + property observer를 사용하는 것도 맞는거 같다.

**Comment by pjy7814** [comment]
https://ontheswift.tistory.com/20
