### ISSUE TITLE
GIT

### ISSUE THREAD

**Issue by papav-hub** [kpuce2022CD/CACA#7]

**Comment by papav-hub** [comment]
- local 저장소 연결
https://blog.gaerae.com/2015/05/git-server-for-windows.html
- 특정 서버
https://blog.gaerae.com/2015/05/git-server-for-windows.html
- git 서버 (요금)
https://blog.lael.be/post/5476
- connect SQL server database to git repository
https://knowledgebase.apexsql.com/link-sql-server-database-git-repository/

**Comment by papav-hub** [comment]
https://blog.lael.be/post/5476

**Comment by papav-hub** [comment]
<git>
- 원격 저장소 관련 자료
https://saakmiso.tistory.com/m/9 
: aws & git 연동 및 독자적인 시스템 생성 관련 자료
https://jexe.tistory.com/8
: git 프로젝트 관리 시스템 구축 관련 자료
https://hoodiejun.tistory.com/15
: 나만의 git 서버 만들기 (local 만 가능)
+) 추가 자료
https://m.blog.naver.com/jydev/220790906889
: SVN server (git 아님)
https://soyoja.com/m/412
: 개인 형상 관리 서버 만들기

**Comment by xoghk5746** [comment]
https://ithub.tistory.com/47 <- ec2 사용법

https://luji.tistory.com/6 <- ec2 서버 생성

https://velog.io/@ckstn0777/AWS-EC2-DB-%EA%B5%AC%EC%B6%95MariaDB <- ec2 db 구축 (마리아DB)

https://sasca37.tistory.com/85 <- ec2, rds 인스턴스 생성 및 db 연결

https://kkkapuq.tistory.com/80 <- rds 사용하지 않고, mysql에 연동

Git 관련 연동 되는지 여부 추가 확인

**Comment by pjy7814** [comment]
웹사이트에 깃 설정하기
https://www.youtube.com/watch?v=ju9loeXNVW0

**Comment by Jimin731** [comment]
<서버>
vapor
- 스위프트로 작성 가능한 웹 서버 프레임워크.
- https://zeddios.tistory.com/957
AWS Lambda
- 서버리스(코드 용량 최대 250MB, 매달 1,000,000 함수 호출 무료).
- https://github.com/swift-server/swift-aws-lambda-runtime
- https://blog.wonizz.tk/2019/09/10/aws-lambda/

<DB>
FaunaDB
- 서버리스 데이터베이스. 
- https://ichi.pro/ko/faunadb-baeg-eob-jadonghwa-122466817535708
- https://github.com/fauna/faunadb-swift (스위프트와 연동 가능)

**Comment by papav-hub** [comment]
<< git 서버 구축 자료조사 완료 >>

**Comment by papav-hub** [comment]
- 동영상에서 설명하는 사이트
: https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server

**Comment by papav-hub** [comment]
- Git 사용자 권한 추가
![image](https://user-images.githubusercontent.com/67986703/146976786-786f9c6f-05ed-41c2-acf7-3afec0d577d6.png)
: https://git-scm.com/book/ko/v2/Git-%EC%84%9C%EB%B2%84-%EC%84%9C%EB%B2%84%EC%97%90-Git-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0
: https://serverfault.com/questions/26954/how-do-i-share-a-git-repository-with-multiple-users-on-a-machine

**Comment by papav-hub** [comment]
- 특정 사용자의 커밋 확인하기
https://webisfree.com/2021-10-18/git-commit%EC%97%90%EC%84%9C-%ED%8A%B9%EC%A0%95-%EC%82%AC%EC%9A%A9%EC%9E%90%EC%9D%98-%EC%BB%A4%EB%B0%8B-%EB%82%B4%EC%9A%A9%EB%A7%8C-%EC%B0%BE%EA%B8%B0-%EA%B2%80%EC%83%89%ED%95%98%EA%B8%B0-log

**Comment by pjy7814** [comment]
Ssh 공개키 만들기
https://git-scm.com/book/ko/v2/Git-%EC%84%9C%EB%B2%84-SSH-%EA%B3%B5%EA%B0%9C%ED%82%A4-%EB%A7%8C%EB%93%A4%EA%B8%B0

Git ssh 연계 : git —bare로 프로젝트생성 가능
https://www.lesstif.com/gitbook/git-bare-repository-http-ssh-13631599.html

https://git-scm.com/book/ko/v2/Git-%EC%84%9C%EB%B2%84-%EC%84%9C%EB%B2%84%EC%97%90-Git-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0 (공식문서)

**Comment by pjy7814** [comment]
git graph
https://git-scm.com/docs/commit-graph
