### ISSUE TITLE
kafka

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#71]

**Comment by papavhub** [comment]
kafka-springboot mp4
https://morioh.com/p/2bd3c2db1555

**Comment by papavhub** [comment]
![image](https://user-images.githubusercontent.com/67986703/163300036-e14e7e14-8d02-40a5-9aba-e70589158450.png)
https://www.code4copy.com/java/kafka-spring-boot-producer-consumer/

**Comment by papavhub** [comment]
kafka + db
https://devel-lee.tistory.com/52

**Comment by papavhub** [comment]
https://leeyh0216.github.io/posts/kafka_docker/

**Comment by papavhub** [comment]
kafka return 정답
https://soft.plusblog.co.kr/30

**Comment by pjy7814** [comment]
**### 아파치 카프카 컨슈머(Kafka Consumer) 자바(Java)예제 코드**
https://soft.plusblog.co.kr/30
