### ISSUE TITLE
iOS CI/CD

### ISSUE THREAD

**Issue by papavhub** [kpuce2022CD/CACA#78]

**Comment by papavhub** [comment]
iOS Continuous CI / CD 구축해보자! - Overview
https://hucet.tistory.com/60

**Comment by papavhub** [comment]
[CI/CD] Github Actions 를 이용한 xcode build & test 자동화
https://sujinnaljin.medium.com/ci-cd-github-actions-%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-xcode-build-test-%EC%9E%90%EB%8F%99%ED%99%94-73b90a3dcc65

**Comment by papavhub** [comment]
iOS command build script
https://magicmon.tistory.com/221

**Comment by pjy7814** [comment]
[명령줄에서 Xcode 7 UI 테스트 실행]

https://krausefx.com/blog/run-xcode-7-ui-tests-from-the-command-line

**Comment by pjy7814** [comment]
xcodebuild Schemes list
$ xcodebuild -list

**Comment by pjy7814** [comment]
create Schemes

https://shockoe.com/ideas/development/how-to-setup-configurations-and-schemes-in-xcode/

**Comment by papavhub** [comment]
(base) hyeminchoi@Hyeui-MacBookPro Clonet % 
xcodebuild -workspace Clonet.xcworkspace \
           -scheme ClonetUITests \
           -destination 'platform=iOS Simulator,OS=15.2,name=iPad (9th generation)'
           test

**Comment by papavhub** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/67986703/174722600-0424e0b9-8cc9-4c0a-b172-0f35fe7b0613.png">
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/67986703/174722625-508ba19b-357e-40eb-aa48-f81778693695.png">
