### ISSUE TITLE
관련 기사

### ISSUE THREAD

**Issue by pjy7814** [kpuce2022CD/CACA#9]
https://news.kbs.co.kr/news/view.do?ncd=4232462
https://m.wowtv.co.kr/NewsCenter/News/Read?articleId=A202007010316
https://www.edaily.co.kr/news/read?newsId=01151286628918376&mediaCodeNo=257

**Comment by papav-hub** [comment]
+ 아이패드 패드로 많이 그린다는 자료임

**Comment by papav-hub** [comment]
<< PSD 많이 사용한다는 근거 >>

**Comment by Jimin731** [comment]
Psd 많이 사용한다는 근거
- 태블릿에서 가장 많이 이용되는 그림그리는 프로그램들의 확장자
- 이비스 페인트 [iPad] - Clip, psd
- CLIP STUDIO PAINT [iPad/Android] Clip, psd
- Adobe Fresco [iPad/Windows] jpg, psd ,pdf
- Procreate [iPad] procreate, psd
- MediBangPaint [iPad/Android] psd

- https://digital-photography-school.com/what-is-the-best-file-format-to-save-your-photos-in-psd-tiff-jpeg-gif-png/ (사진 저장을 위한 파일 형식에 대해)
- https://www.dailypop.kr/news/articleView.html?idxno=46913 (아이패드 그림용 어플 선호도)
- 아이패드 그림 앱이 psd 확장자를 사용한다는 사례는 많으나 psd이용률에 대한 통계량은 얻기 어렵다.

**Comment by xoghk5746** [comment]
문헌 정리 (관련 기사 및 연구)
셔터스톡. 이미지 컬렉션을 공유하는 방법. 
https://support.shutterstock.com/s/article/How-can-I-share-my-lightbox-with-other-people?language=ko

https://www.jungle.co.kr/magazine/27014 <- 셔터스톡의 홍보효과 및 차별화. (어느정도 벤치마킹 필요)

디자인 협업 도구들. (줌, 트렐로, 슬랙 같은 익숙한 프로그램도 있음.)
https://www.shutterstock.com/ko/blog/design-collaboration-tools/

이를 공유하고, 피드백을 줄 수 있는 방법들은 다양하지만
여러가지 툴을 번갈아가면서 써야되는 불편함과, 직접적으로 특정 사용자의 레이어만 추출하고
이를 부분수정을 거치거나, 이러한 과정 하나하나를 따로 저장하여 볼 수 있는 방법은 없음.

특장점 - 직접 수정 및 코멘트, 특정 사용자 작업 모니터링, 과정 저장, 웹 포트폴리오 사이트

**Comment by papav-hub** [comment]
<문헌>
- 애플리케이션에 Git 넣기 (Libgit2)
https://git-scm.com/book/ko/v2/
- Git Server Setting
https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server
- Architecture 참고
https://docs.gitlab.com/ee/development/architecture.html
- DB 참고
https://ghtorrent.org/relational.html
- 이미지 파일 명령줄 조작
https://imagemagick.org/

**Comment by Jimin731** [comment]
참고 문헌
Swift - https://developer.apple.com/documentation/swift
UIKit - https://developer.apple.com/documentation/uikit

**Comment by pjy7814** [comment]
<문헌>

깃 서버 공식 문서(https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols)
