### ISSUE TITLE
Restart EC2

### ISSUE THREAD

**Issue by pjy7814** [kpuce2022CD/CACA#94]
- [ ] apache 확인 (http://3.35.46.50/images/)
- [ ] pm2 서버
- [ ] clone 확인
- [ ] commit, push 확인

**Comment by papavhub** [comment]
sudo service apache2 restart
sudo systemctl start docker
cd jenkins
sudo docker-compose up --build -d
cd ../apollo
pm2 start login.js
pm2 start accept_user.js

sudo chown -R ubuntu:www-data /var/www/html
sudo chmod -R g+sw /var/www/html
sudo a2enmod cgi alias env rewrite
htpasswd -c /var/www/html/.htpasswd ubuntu
sudo service apache2 restart
